// Auto-generated by src.publish.core.export_config — do not edit.
// Re-generate: python -m src.publish.runner --league nba --export-config
var CONFIG = {
  "sheet_id": "1kqVNHu8cs4lFAEAflI4Ow77oEZEusX7_VpQ6xt8CgB4",
  "league": {
    "name": "NBA",
    "slug": "nba",
    "teams_key": "nba_teams",
    "players_tab_names": [
      "NBA",
      "PLAYERS",
      "ALL_PLAYERS"
    ],
    "players_range_key": "all_players_tab",
    "edit_col_index_key": "nba_col_index"
  },
  "nba_teams": {
    "ATL": 1,
    "BKN": 3,
    "BOS": 2,
    "CHA": 4,
    "CHI": 5,
    "CLE": 6,
    "DAL": 7,
    "DEN": 8,
    "DET": 9,
    "GSW": 10,
    "HOU": 11,
    "IND": 12,
    "LAC": 13,
    "LAL": 14,
    "MEM": 15,
    "MIA": 16,
    "MIL": 17,
    "MIN": 18,
    "NOP": 19,
    "NYK": 20,
    "OKC": 21,
    "ORL": 22,
    "PHI": 23,
    "PHX": 24,
    "POR": 25,
    "SAC": 26,
    "SAS": 27,
    "TOR": 28,
    "UTA": 29,
    "WAS": 30
  },
  "team_name_to_abbr": {
    "Atlanta Hawks": "ATL",
    "Brooklyn Nets": "BKN",
    "Boston Celtics": "BOS",
    "Charlotte Hornets": "CHA",
    "Chicago Bulls": "CHI",
    "Cleveland Cavaliers": "CLE",
    "Dallas Mavericks": "DAL",
    "Denver Nuggets": "DEN",
    "Detroit Pistons": "DET",
    "Golden State Warriors": "GSW",
    "Houston Rockets": "HOU",
    "Indiana Pacers": "IND",
    "LA Clippers": "LAC",
    "Los Angeles Lakers": "LAL",
    "Memphis Grizzlies": "MEM",
    "Miami Heat": "MIA",
    "Milwaukee Bucks": "MIL",
    "Minnesota Timberwolves": "MIN",
    "New Orleans Pelicans": "NOP",
    "New York Knicks": "NYK",
    "Oklahoma City Thunder": "OKC",
    "Orlando Magic": "ORL",
    "Philadelphia 76ers": "PHI",
    "Phoenix Suns": "PHX",
    "Portland Trail Blazers": "POR",
    "Sacramento Kings": "SAC",
    "San Antonio Spurs": "SAS",
    "Toronto Raptors": "TOR",
    "Utah Jazz": "UTA",
    "Washington Wizards": "WAS"
  },
  "stat_columns": [
    "szn",
    "gms",
    "min",
    "pace",
    "pts",
    "p/ta",
    "2a",
    "p/2",
    "ora",
    "p/or",
    "cra",
    "p/cr",
    "uar",
    "oma",
    "p/om",
    "cma",
    "p/cm",
    "uam",
    "3a",
    "p/3",
    "o3a",
    "p/o3",
    "c3a",
    "p/c3",
    "ua3",
    "tftr",
    "p/ft",
    "dnk",
    "tou",
    "spt",
    "%trs",
    "%trp",
    "%trt",
    "ast",
    "past",
    "2ast",
    "tov",
    "or%",
    "cor%",
    "dr%",
    "cdr%",
    "pb%",
    "odst",
    "ddst",
    "dra",
    "p/dr",
    "dma",
    "p/dm",
    "d3a",
    "p/d3",
    "cont",
    "blk",
    "defl",
    "stl",
    "st+c",
    "fls",
    "w%",
    "ortg",
    "drtg",
    "nooo",
    "ndoo"
  ],
  "reverse_stats": [
    "age",
    "spt",
    "%trt",
    "tov",
    "p/dr",
    "p/dm",
    "p/d3",
    "fls",
    "drtg",
    "ndoo"
  ],
  "editable_fields": null,
  "editable_columns": [
    {
      "col_key": "ws",
      "team_col_index": 12,
      "nba_col_index": 13,
      "db_field": "{wingspan_ins}",
      "display_name": "Wingspan in Feet'Inches\" (Editable)",
      "format": "measurement",
      "team_row_calc": null
    },
    {
      "col_key": "🖐️",
      "team_col_index": 14,
      "nba_col_index": 15,
      "db_field": "{hand}",
      "display_name": "Handedness (Editable)",
      "format": "number",
      "team_row_calc": null
    },
    {
      "col_key": "notes",
      "team_col_index": 16,
      "nba_col_index": 17,
      "db_field": "{notes}",
      "display_name": "Personal thoughts, observations, findings, etc (Editable)",
      "format": "number",
      "team_row_calc": null
    }
  ],
  "column_indices": {
    "player_id": 1,
    "team": 2,
    "stats_start": 9
  },
  "section_boundaries": {
    "team_tab": [
      {
        "col": 15,
        "hp": false
      },
      {
        "col": 17,
        "hp": false
      },
      {
        "col": 136,
        "hp": false
      },
      {
        "col": 255,
        "hp": false
      },
      {
        "col": 374,
        "hp": false
      },
      {
        "col": 495,
        "hp": false
      },
      {
        "col": 616,
        "hp": false
      },
      {
        "col": 737,
        "hp": false
      },
      {
        "col": 858,
        "hp": false
      },
      {
        "col": 979,
        "hp": false
      },
      {
        "col": 1100,
        "hp": false
      },
      {
        "col": 1221,
        "hp": false
      },
      {
        "col": 1342,
        "hp": false
      },
      {
        "col": 1463,
        "hp": false
      },
      {
        "col": 1584,
        "hp": false
      },
      {
        "col": 1705,
        "hp": false
      },
      {
        "col": 1826,
        "hp": false
      },
      {
        "col": 1947,
        "hp": false
      },
      {
        "col": 2068,
        "hp": false
      },
      {
        "col": 2189,
        "hp": false
      },
      {
        "col": 2310,
        "hp": false
      },
      {
        "col": 2431,
        "hp": false
      },
      {
        "col": 2552,
        "hp": false
      },
      {
        "col": 2673,
        "hp": false
      },
      {
        "col": 2794,
        "hp": false
      },
      {
        "col": 2915,
        "hp": false
      },
      {
        "col": 3036,
        "hp": false
      },
      {
        "col": 3157,
        "hp": false
      },
      {
        "col": 3278,
        "hp": false
      }
    ],
    "all_players_tab": [
      {
        "col": 16,
        "hp": false
      },
      {
        "col": 18,
        "hp": false
      },
      {
        "col": 135,
        "hp": false
      },
      {
        "col": 252,
        "hp": false
      },
      {
        "col": 369,
        "hp": false
      },
      {
        "col": 488,
        "hp": false
      },
      {
        "col": 607,
        "hp": false
      },
      {
        "col": 726,
        "hp": false
      },
      {
        "col": 845,
        "hp": false
      },
      {
        "col": 964,
        "hp": false
      },
      {
        "col": 1083,
        "hp": false
      },
      {
        "col": 1202,
        "hp": false
      },
      {
        "col": 1321,
        "hp": false
      },
      {
        "col": 1440,
        "hp": false
      },
      {
        "col": 1559,
        "hp": false
      },
      {
        "col": 1678,
        "hp": false
      },
      {
        "col": 1797,
        "hp": false
      },
      {
        "col": 1916,
        "hp": false
      },
      {
        "col": 2035,
        "hp": false
      },
      {
        "col": 2154,
        "hp": false
      },
      {
        "col": 2273,
        "hp": false
      },
      {
        "col": 2392,
        "hp": false
      },
      {
        "col": 2511,
        "hp": false
      },
      {
        "col": 2630,
        "hp": false
      },
      {
        "col": 2749,
        "hp": false
      },
      {
        "col": 2868,
        "hp": false
      },
      {
        "col": 2987,
        "hp": false
      },
      {
        "col": 3106,
        "hp": false
      },
      {
        "col": 3225,
        "hp": false
      }
    ],
    "all_teams_tab": [
      {
        "col": 14,
        "hp": false
      },
      {
        "col": 16,
        "hp": false
      },
      {
        "col": 131,
        "hp": false
      },
      {
        "col": 246,
        "hp": false
      },
      {
        "col": 361,
        "hp": false
      },
      {
        "col": 478,
        "hp": false
      },
      {
        "col": 595,
        "hp": false
      },
      {
        "col": 712,
        "hp": false
      },
      {
        "col": 829,
        "hp": false
      },
      {
        "col": 946,
        "hp": false
      },
      {
        "col": 1063,
        "hp": false
      },
      {
        "col": 1180,
        "hp": false
      },
      {
        "col": 1297,
        "hp": false
      },
      {
        "col": 1414,
        "hp": false
      },
      {
        "col": 1531,
        "hp": false
      },
      {
        "col": 1648,
        "hp": false
      },
      {
        "col": 1765,
        "hp": false
      },
      {
        "col": 1882,
        "hp": false
      },
      {
        "col": 1999,
        "hp": false
      },
      {
        "col": 2116,
        "hp": false
      },
      {
        "col": 2233,
        "hp": false
      },
      {
        "col": 2350,
        "hp": false
      },
      {
        "col": 2467,
        "hp": false
      },
      {
        "col": 2584,
        "hp": false
      },
      {
        "col": 2701,
        "hp": false
      },
      {
        "col": 2818,
        "hp": false
      },
      {
        "col": 2935,
        "hp": false
      },
      {
        "col": 3052,
        "hp": false
      },
      {
        "col": 3169,
        "hp": false
      }
    ]
  },
  "subsection_boundaries": {
    "team_tab": [],
    "all_players_tab": [],
    "all_teams_tab": []
  },
  "always_hidden_columns": {
    "team_tab": [
      5,
      15,
      17,
      24,
      67,
      86,
      97,
      102,
      125,
      136,
      143,
      186,
      205,
      216,
      221,
      244,
      255,
      262,
      305,
      324,
      335,
      340,
      363,
      374,
      383,
      426,
      445,
      456,
      461,
      484,
      495,
      504,
      547,
      566,
      577,
      582,
      605,
      616,
      625,
      668,
      687,
      698,
      703,
      726,
      737,
      746,
      789,
      808,
      819,
      824,
      847,
      858,
      867,
      910,
      929,
      940,
      945,
      968,
      979,
      988,
      1031,
      1050,
      1061,
      1066,
      1089,
      1100,
      1109,
      1152,
      1171,
      1182,
      1187,
      1210,
      1221,
      1230,
      1273,
      1292,
      1303,
      1308,
      1331,
      1342,
      1351,
      1394,
      1413,
      1424,
      1429,
      1452,
      1463,
      1472,
      1515,
      1534,
      1545,
      1550,
      1573,
      1584,
      1593,
      1636,
      1655,
      1666,
      1671,
      1694,
      1705,
      1714,
      1757,
      1776,
      1787,
      1792,
      1815,
      1826,
      1835,
      1878,
      1897,
      1908,
      1913,
      1936,
      1947,
      1956,
      1999,
      2018,
      2029,
      2034,
      2057,
      2068,
      2077,
      2120,
      2139,
      2150,
      2155,
      2178,
      2189,
      2198,
      2241,
      2260,
      2271,
      2276,
      2299,
      2310,
      2319,
      2362,
      2381,
      2392,
      2397,
      2420,
      2431,
      2440,
      2483,
      2502,
      2513,
      2518,
      2541,
      2552,
      2561,
      2604,
      2623,
      2634,
      2639,
      2662,
      2673,
      2682,
      2725,
      2744,
      2755,
      2760,
      2783,
      2794,
      2803,
      2846,
      2865,
      2876,
      2881,
      2904,
      2915,
      2924,
      2967,
      2986,
      2997,
      3002,
      3025,
      3036,
      3045,
      3088,
      3107,
      3118,
      3123,
      3146,
      3157,
      3166,
      3209,
      3228,
      3239,
      3244,
      3267,
      3278
    ],
    "all_teams_tab": [
      2,
      5,
      14,
      16,
      23,
      66,
      85,
      96,
      101,
      124,
      131,
      138,
      181,
      200,
      211,
      216,
      239,
      246,
      253,
      296,
      315,
      326,
      331,
      354,
      361,
      370,
      413,
      432,
      443,
      448,
      471,
      478,
      487,
      530,
      549,
      560,
      565,
      588,
      595,
      604,
      647,
      666,
      677,
      682,
      705,
      712,
      721,
      764,
      783,
      794,
      799,
      822,
      829,
      838,
      881,
      900,
      911,
      916,
      939,
      946,
      955,
      998,
      1017,
      1028,
      1033,
      1056,
      1063,
      1072,
      1115,
      1134,
      1145,
      1150,
      1173,
      1180,
      1189,
      1232,
      1251,
      1262,
      1267,
      1290,
      1297,
      1306,
      1349,
      1368,
      1379,
      1384,
      1407,
      1414,
      1423,
      1466,
      1485,
      1496,
      1501,
      1524,
      1531,
      1540,
      1583,
      1602,
      1613,
      1618,
      1641,
      1648,
      1657,
      1700,
      1719,
      1730,
      1735,
      1758,
      1765,
      1774,
      1817,
      1836,
      1847,
      1852,
      1875,
      1882,
      1891,
      1934,
      1953,
      1964,
      1969,
      1992,
      1999,
      2008,
      2051,
      2070,
      2081,
      2086,
      2109,
      2116,
      2125,
      2168,
      2187,
      2198,
      2203,
      2226,
      2233,
      2242,
      2285,
      2304,
      2315,
      2320,
      2343,
      2350,
      2359,
      2402,
      2421,
      2432,
      2437,
      2460,
      2467,
      2476,
      2519,
      2538,
      2549,
      2554,
      2577,
      2584,
      2593,
      2636,
      2655,
      2666,
      2671,
      2694,
      2701,
      2710,
      2753,
      2772,
      2783,
      2788,
      2811,
      2818,
      2827,
      2870,
      2889,
      2900,
      2905,
      2928,
      2935,
      2944,
      2987,
      3006,
      3017,
      3022,
      3045,
      3052,
      3061,
      3104,
      3123,
      3134,
      3139,
      3162,
      3169
    ],
    "all_players_tab": []
  },
  "stats_section_ranges": {
    "team_tab": null,
    "all_players_tab": null,
    "all_teams_tab": null
  },
  "default_stat_rate": "per_possession",
  "subsection_row_index": 3,
  "all_teams_editable_columns": [
    {
      "col_key": "notes",
      "col_index": 15,
      "db_field": "{notes}",
      "display_name": "Personal thoughts, observations, findings, etc (Editable)"
    }
  ],
  "colors": {
    "red": {
      "r": 237,
      "g": 74,
      "b": 43
    },
    "yellow": {
      "r": 251,
      "g": 245,
      "b": 95
    },
    "green": {
      "r": 75,
      "g": 186,
      "b": 22
    }
  },
  "color_thresholds": {
    "low": 0,
    "mid": 50,
    "high": 100
  },
  "layout": {
    "header_row_count": 6,
    "data_start_row": 6,
    "frozen_rows": 6,
    "frozen_cols": 1
  },
  "sections": {
    "entities": {
      "display_name": "Names",
      "is_stats_section": false,
      "toggleable": false
    },
    "profile": {
      "display_name": "Profile",
      "is_stats_section": false,
      "toggleable": true
    },
    "evaluation": {
      "display_name": "Evaluation",
      "is_stats_section": false,
      "toggleable": true
    },
    "current_stats": {
      "display_name": "Current Stats",
      "is_stats_section": true,
      "toggleable": true
    },
    "historical_stats": {
      "display_name": "Historical Stats",
      "is_stats_section": true,
      "toggleable": true
    },
    "postseason_stats": {
      "display_name": "Postseason Stats",
      "is_stats_section": true,
      "toggleable": true
    },
    "identity": {
      "display_name": "Identity",
      "is_stats_section": false,
      "toggleable": false
    }
  },
  "subsections": {
    "League": "League",
    "Player": "Player",
    "rates": "Rates",
    "scoring": "Scoring",
    "ball_management": "Ball Management",
    "rebounding": "Rebounding",
    "distance": "Distance",
    "defense": "Defense",
    "opponent": "Opponent",
    "team_ratings": "Team Ratings"
  },
  "stat_rates": [
    "per_possession",
    "per_game",
    "per_minute"
  ],
  "stat_rate_labels": {
    "per_possession": "per 100 Poss",
    "per_game": "per Game",
    "per_minute": "per 40 Mins"
  },
  "menu": {
    "historical_timeframe": {
      "display_name": "Historical Timeframe",
      "max_value": 20
    },
    "stats_rate": {
      "display_name": "Stats Rate"
    },
    "stats_mode": {
      "display_name": "Stats Mode",
      "show_label": "Show Advanced",
      "hide_label": "Show Basic"
    }
  },
  "max_historical_timeframe": 20,
  "supported_historical_timeframes": [
    1,
    3,
    5,
    7
  ],
  "editable_lookup": {
    "ws": {
      "db_field": "{wingspan_ins}",
      "display_name": "Wingspan in Feet'Inches\" (Editable)",
      "format": "measurement",
      "team_row_calc": null,
      "indices": {
        "all_players_tab": 13
      }
    },
    "🖐️": {
      "db_field": "{hand}",
      "display_name": "Handedness (Editable)",
      "format": "number",
      "team_row_calc": null,
      "indices": {
        "all_players_tab": 15
      }
    },
    "notes": {
      "db_field": "{notes}",
      "display_name": "Personal thoughts, observations, findings, etc (Editable)",
      "format": "number",
      "team_row_calc": null,
      "indices": {
        "all_players_tab": 17
      }
    }
  }
};

// --- Auto-generated Menu Wrappers ---
function show_profile() { _setSectionVisibility('profile', true, 'Profile shown'); }
function hide_profile() { _setSectionVisibility('profile', false, 'Profile hidden'); }
function show_evaluation() { _setSectionVisibility('evaluation', true, 'Evaluation shown'); }
function hide_evaluation() { _setSectionVisibility('evaluation', false, 'Evaluation hidden'); }
function show_current_stats() { _setSectionVisibility('current_stats', true, 'Current Stats shown'); }
function hide_current_stats() { _setSectionVisibility('current_stats', false, 'Current Stats hidden'); }
function show_historical_stats() { _setSectionVisibility('historical_stats', true, 'Historical Stats shown'); }
function hide_historical_stats() { _setSectionVisibility('historical_stats', false, 'Historical Stats hidden'); }
function show_postseason_stats() { _setSectionVisibility('postseason_stats', true, 'Postseason Stats shown'); }
function hide_postseason_stats() { _setSectionVisibility('postseason_stats', false, 'Postseason Stats hidden'); }
function switchTo_per_possession() { _switchStatRate('per_possession'); }
function switchTo_per_game() { _switchStatRate('per_game'); }
function switchTo_per_minute() { _switchStatRate('per_minute'); }
function setTimeframe1() { _setTimeframe(1); }
function setTimeframe3() { _setTimeframe(3); }
function setTimeframe5() { _setTimeframe(5); }
function setTimeframe7() { _setTimeframe(7); }
