"""
THE GLASS - Display Configuration
Single source of truth for all display logic, calculations, formatting, and percentiles.

This config drives:
- Sheet column generation (src/sheets.py)
- Stat calculations (lib/sheets.py)
- Percentile generation (auto-generated columns)
- Section organization (player_info, analysis, rates, scoring, ball_management, rebounding, defense, onoff, identity)
"""

import os

from config.sheets import (  # noqa: F401 — re-exported
    COLORS, COLOR_THRESHOLDS, SHEET_FORMATTING,
    SECTION_CONFIG, SECTIONS, COLUMN_DEFAULTS,
    API_CONFIG, SERVER_CONFIG,
)

# ============================================================================
# GOOGLE SHEETS CONFIGURATION
# ============================================================================

GOOGLE_SHEETS_CONFIG = {
    'credentials_file': os.getenv('GOOGLE_CREDENTIALS_FILE'),
    'spreadsheet_id': os.getenv('GOOGLE_SPREADSHEET_ID'),
    'spreadsheet_name': os.getenv('GOOGLE_SPREADSHEET_NAME'),
    'scopes': [
        'https://www.googleapis.com/auth/spreadsheets',
        'https://www.googleapis.com/auth/drive'
    ],
}

# ============================================================================
# STAT CALCULATION CONSTANTS
# ============================================================================

STAT_CONSTANTS = {
    'game_length_minutes': 48.0,        # NBA game length
    'default_per_minutes': 48.0,        # Per 48 Min (standardized across leagues)
    'default_per_possessions': 100.0,   # Default possessions for per-possession stats
    'cache_ttl_seconds': 300,           # API response cache TTL
}

# ============================================================================
# STAT MODE CONFIGURATION
# ============================================================================

# All stat modes that are pre-built into every sheet.
# Mode switching is instant via column visibility toggles (no re-sync needed).
STAT_MODES = ['per_100', 'per_game', 'per_48']
DEFAULT_STAT_MODE = 'per_100'

# ============================================================================
# SECTION AND SUBSECTION DEFINITIONS
# ============================================================================

# Section display configuration - defines how each section appears in sheets
# SECTION_CONFIG — imported from config.sheets

# Stat subsections - correspond to Row 2 subsection headers (within current_stats/historical_stats/postseason_stats)
SUBSECTIONS = [
    'rates',          # Games, Minutes, Possessions
    'scoring',        # Points, TS%, 2fg/3, Rim/Mid/3PT tracking, FT
    'ball_management',   # Touches, Assists, Potential Assists, Turnovers
    'rebounding',     # OREB%, DREB%, Contested OREB/DREB%, Putbacks
    'movement',       # Offensive/Defensive distance traveled
    'defense',        # Defended shots, Steals, Deflections, Blocks, Contests, Charges, Fouls
    'opponent',       # All opponent stats (Teams sheet only, between defense and on/off)
    'onoff',          # Offensive/Defensive Rating, Off-court ratings
]

# Display names for subsections — used in header row
SUBSECTION_DISPLAY_NAMES = {
    'rates': 'Rates',
    'scoring': 'Scoring',
    'ball_management': 'Ball Management',
    'rebounding': 'Rebounding',
    'movement': 'Movement',
    'defense': 'Defense',
    'opponent': 'Opponent',
    'onoff': 'On/Off',
}

# SECTIONS — imported from config.sheets


# ============================================================================
# COLORS & PERCENTILES — imported from config.sheets
# ============================================================================


# ============================================================================
# SHEET FORMATTING — imported from config.sheets
# ============================================================================

# ============================================================================
# SHEETS_COLUMNS - Master dictionary for all display columns
# ============================================================================

SHEETS_COLUMNS = {

    'names': {
        'stat_category': 'none',
        'display_name': 'Names',
        'description': 'player name / team name',
        'section': ['entities'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'name',
        'team_formula': 'TEAM',
        'opponents_formula': 'OPPONENTS',
        'minimum_width': 'auto',
    },
    
    'team': {
        'stat_category': 'none',
        'display_name': 'Tm',
        'description': 'team abbreviation',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_players'],
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'team_abbr',
        'team_formula': None,
        'opponents_formula': None,
        'minimum_width': 35,
    },
    
    'jersey': {
        'stat_category': 'none',
        'display_name': '#',
        'description': 'jersey number',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'jersey_number',
        'team_formula': None,
        'opponents_formula': None,
        'minimum_width': 20,
    },
    
    'experience': {
        'stat_category': 'none',
        'display_name': 'Exp',
        'description': 'years of NBA experience',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'years_experience',
        'team_formula': 'years_experience',
        'opponents_formula': None,
        'minimum_width': 32,
    },
    
    'age': {
        'stat_category': 'none',
        'display_name': 'Age',
        'description': 'player age',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'age',
        'team_formula': 'age',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'height': {
        'stat_category': 'none',
        'display_name': 'Ht',
        'description': 'height',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'height',
        'decimal_places': 1,
        'player_formula': 'height_inches',
        'team_formula': 'height_inches',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'weight': {
        'stat_category': 'none',
        'display_name': 'Wt',
        'description': 'weight',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'weight_lbs',
        'team_formula': 'weight_lbs',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'wingspan': {
        'stat_category': 'none',
        'display_name': 'WS',
        'description': 'wingspan',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': False,
        'editable': True,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'height',
        'decimal_places': 1,
        'player_formula': 'wingspan_inches',
        'team_formula': 'wingspan_inches',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'hand': {
        'stat_category': 'none',
        'display_name': '🖐️',
        'description': 'handedness',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': True,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'hand',
        'team_formula': None,
        'opponents_formula': None,
        'minimum_width': 20,
    },
    
    'notes': {
        'stat_category': 'none',
        'display_name': 'Notes',
        'description': 'Scouting notes (editable)',
        'section': ['analysis'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': True,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'notes',
        'team_formula': 'notes',
        'opponents_formula': None,
        'minimum_width': 500,
    },

    'years': {
        'stat_category': 'none',
        'display_name': 'Yrs',
        'description': 'Number of seasons in range',
        'section': ['historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'nullable': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'year',
        'team_formula': 'year',
        'opponents_formula': None,
        'minimum_width': 30,
    },
        
    'games': {
        'stat_category': 'none',
        'display_name': 'GMS',
        'description': 'Games played',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'nullable': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'games',
        'team_formula': 'games',
        'opponents_formula': None,
        'minimum_width': 30,
    },
    
    'minutes': {
        'stat_category': 'none',
        'display_name': 'Min',
        'description': 'Minutes played',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': 'per_game_only',
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'minutes_x10 / 10',
        'team_formula': 'minutes_x10 / 10',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'pace': {
        'stat_category': 'basic',
        'display_name': 'Pace',
        'description': 'Possessions per minute',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '(48 / (minutes_x10 / 10)) * possessions',
        'team_formula': '(48 / (minutes_x10 / 10)) * possessions',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'points': {
        'stat_category': 'basic',
        'display_name': 'PTS',
        'description': 'Total points scored',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '(2fgm * 2) + (3fgm * 3) + ftm',
        'team_formula': '(2fgm * 2) + (3fgm * 3) + ftm',
        'opponents_formula': '(opp_2fgm * 2) + (opp_3fgm * 3) + opp_ftm',
        'minimum_width': 35,
    },
    
    'true_points_per_shot_attempt': {
        'stat_category': 'basic',
        'display_name': 'TPS',
        'description': 'Points per true shot attempt (2FGA + 3FGA + 0.44*FTA)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '((2fgm * 2) + (3fgm * 3) + ftm) / (2fga + 3fga + 0.44 * fta)',
        'team_formula': '((2fgm * 2) + (3fgm * 3) + ftm) / (2fga + 3fga + 0.44 * fta)',
        'opponents_formula': '((opp_2fgm * 2) + (opp_3fgm * 3) + opp_ftm) / (opp_2fga + opp_3fga + 0.44 * opp_fta)',
        'minimum_width': 'auto',
    },
    
    '2fga': {
        'stat_category': 'basic',
        'display_name': '2A',
        'description': 'Two-point field goal attempts',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'basic',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '2fga',
        'team_formula': '2fga',
        'opponents_formula': 'opp_2fga',
        'minimum_width': 'auto',
    },
    
    'Points_Per_Two_attempt': {
        'stat_category': 'basic',
        'display_name': 'P2',
        'description': 'Points per two-point attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'basic',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2 * (2fgm / 2fga)',
        'team_formula': '2 * (2fgm / 2fga)',
        'opponents_formula': '2 * (opp_2fgm / opp_2fga)',
        'minimum_width': 'auto',
    },
    
    'cont_close_2fga': {
        'stat_category': 'tracking',
        'display_name': 'CC2A',
        'description': 'Contested close two-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'cont_close_2fga',
        'team_formula': 'cont_close_2fga',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'Points_Per_cont_close_2fga': {
        'stat_category': 'tracking',
        'display_name': 'PCC2',
        'description': 'Points per contested close two attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2 * (cont_close_2fgm / cont_close_2fga)',
        'team_formula': '2 * (cont_close_2fgm / cont_close_2fga)',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'open_close_2fga': {
        'stat_category': 'tracking',
        'display_name': 'OC2A',
        'description': 'Open close two-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'open_close_2fga',
        'team_formula': 'open_close_2fga',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'Points_Per_open_close_2fga': {
        'stat_category': 'tracking',
        'display_name': 'POC2',
        'description': 'Points per open close two attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2 * (open_close_2fgm / open_close_2fga)',
        'team_formula': '2 * (open_close_2fgm / open_close_2fga)',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'cont_long_2fga': {
        'stat_category': 'tracking',
        'display_name': 'CL2A',
        'description': 'Contested long two-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'cont_2fga - cont_close_2fga',
        'team_formula': 'cont_2fga - cont_close_2fga',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'points_per_cont_long_2fga': {
        'stat_category': 'tracking',
        'display_name': 'PCL2',
        'description': 'Points per contested long two attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2 * ((cont_2fgm - cont_close_2fgm) / (cont_2fga - cont_close_2fga))',
        'team_formula': '2 * ((cont_2fgm - cont_close_2fgm) / (cont_2fga - cont_close_2fga))',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'open_long_2fga': {
        'stat_category': 'tracking',
        'display_name': 'OL2A',
        'description': 'Open long two-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'open_2fga - open_close_2fga',
        'team_formula': 'open_2fga - open_close_2fga',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'points_per_open_long_2fga': {
        'stat_category': 'tracking',
        'display_name': 'POL2',
        'description': 'Points per open long two attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2* ((open_2fgm - open_close_2fgm) / (open_2fga - open_close_2fga))',
        'team_formula': '2* ((open_2fgm - open_close_2fgm) / (open_2fga - open_close_2fga))',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    '3fga': {
        'stat_category': 'basic',
        'display_name': '3A',
        'description': 'Three-point field goal attempts',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'basic',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '3fga',
        'team_formula': '3fga',
        'opponents_formula': 'opp_3fga',
        'minimum_width': 'auto',
    },
    
    'Points_Per_Three_attempt': {
        'stat_category': 'basic',
        'display_name': 'P3',
        'description': 'Points per three-point attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'basic',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '3 * (3fgm / 3fga)',
        'team_formula': '3 * (3fgm / 3fga)',
        'opponents_formula': '3 * (opp_3fgm / opp_3fga)',
        'minimum_width': 'auto',
    },
    
    'cont_3fga': {
        'stat_category': 'tracking',
        'display_name': 'C3A',
        'description': 'Contested three-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'cont_3fga',
        'team_formula': 'cont_3fga',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'points_per_cont_3fga': {
        'stat_category': 'tracking',
        'display_name': 'PC3',
        'description': 'Points per contested three attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '3 * (cont_3fgm / cont_3fga)',
        'team_formula': '3 * (cont_3fgm / cont_3fga)',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'open_3fga': {
        'stat_category': 'tracking',
        'display_name': 'O3A',
        'description': 'Open three-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'open_3fga',
        'team_formula': 'open_3fga',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'points_per_open_3fga': {
        'stat_category': 'tracking',
        'display_name': 'PO3',
        'description': 'Points per open three attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '3 * (open_3fgm / open_3fga)',
        'team_formula': '3 * (open_3fgm / open_3fga)',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'free_throw_rate': {
        'stat_category': 'basic',
        'display_name': 'FTR',
        'description': 'Free throw attempts per field goal attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 2,
        'mode_overrides': {
            'totals': {
                'display_name': 'FTA',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'fta',
                'team_formula': 'fta',
                'opponents_formula': 'opp_fta',
            },
        },
        'player_formula': 'fta / (2fga + 3fga)',
        'team_formula': 'fta / (2fga + 3fga)',
        'opponents_formula': 'opp_fta / (opp_2fga + opp_3fga)',
        'minimum_width': 'auto',
    },
    
    'points_per_ft': {
        'stat_category': 'basic',
        'display_name': 'PFT',
        'description': 'Points per free throw',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': 'ftm / fta',
        'team_formula': 'ftm / fta',
        'opponents_formula': 'opp_ftm / opp_fta',
        'minimum_width': 'auto',
    },
    
    'dunks': {
        'stat_category': 'tracking',
        'display_name': 'Dnk',
        'description': 'Dunks',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'dunks',
        'team_formula': 'dunks',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'assists': {
        'stat_category': 'basic',
        'display_name': 'AST',
        'description': 'Assists per 100 possessions',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'assists',
        'team_formula': 'assists',
        'opponents_formula': 'opp_assists',
        'minimum_width': 30,
    },
    
    'potential_assists': {
        'stat_category': 'tracking',
        'display_name': 'PAST',
        'description': 'Potential assists (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'pot_assists',
        'team_formula': 'pot_assists',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'secondary_assists': {
        'stat_category': 'tracking',
        'display_name': '2AST',
        'description': 'Secondary assists (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'sec_assists',
        'team_formula': 'sec_assists',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'passes': {
        'stat_category': 'tracking',
        'display_name': 'Pass',
        'description': 'Total passes made (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'passes',
        'team_formula': 'passes',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'touches': {
        'stat_category': 'tracking',
        'display_name': 'Tou',
        'description': 'Total touches (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'touches',
        'team_formula': 'touches',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'seconds_per_touch': {
        'stat_category': 'tracking',
        'display_name': 'SPT',
        'description': 'Average seconds per touch (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '(60 * time_on_ball) / touches',
        'team_formula': '(60 * time_on_ball) / touches',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'dribbles_per_touch': {
        'stat_category': 'tracking',
        'display_name': 'DPT',
        'description': 'Average dribbles per touch (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'dribbles / touches',
        'team_formula': 'dribbles / touches',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'pct_touches_shots': {
        'stat_category': 'tracking',
        'display_name': '%TS',
        'description': 'Percentage of touches that result in a shot (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '((2fga + 3fga + (0.44 * fta)) / touches) * 100',
        'team_formula': '((2fga + 3fga + (0.44 * fta)) / touches) * 100',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'pct_touches_passes': {
        'stat_category': 'tracking',
        'display_name': '%TP',
        'description': 'Percentage of touches that result in a pass (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '(passes / touches) * 100',
        'team_formula': '(passes / touches) * 100',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'pct_touches_turnovers': {
        'stat_category': 'tracking',
        'display_name': '%TT',
        'description': 'Percentage of touches that result in a turnover (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '(turnovers / touches) * 100',
        'team_formula': '(turnovers / touches) * 100',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'turnovers': {
        'stat_category': 'basic',
        'display_name': 'TOV',
        'description': 'Turnovers',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'turnovers',
        'team_formula': 'turnovers',
        'opponents_formula': 'opp_turnovers',
        'minimum_width': 'auto',
    },
    
    'oreb_pct': {
        'stat_category': 'basic',
        'display_name': 'OR%',
        'description': 'Offensive rebound percentage',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'OREB',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'o_rebounds',
                'team_formula': 'o_rebounds',
                'opponents_formula': 'opp_o_rebounds',
            },
        },
        'player_formula': 'o_rebound_pct_x1000 / 10',
        'team_formula': 'o_rebound_pct_x1000 / 10',
        'opponents_formula': None,
        'minimum_width': 30,
    },
    
    'dreb_pct': {
        'stat_category': 'basic',
        'display_name': 'DR%',
        'description': 'Defensive rebound percentage',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'DRS',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'd_rebounds',
                'team_formula': 'd_rebounds',
                'opponents_formula': 'opp_d_rebounds',
            },
        },
        'player_formula': 'd_rebound_pct_x1000 / 10',
        'team_formula': 'd_rebound_pct_x1000 / 10',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'cont_oreb_pct': {
        'stat_category': 'tracking',
        'display_name': 'COR%',
        'description': 'Contested offensive rebound % (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'COR',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'cont_o_rebs',
                'team_formula': 'cont_o_rebs',
                'opponents_formula': None,
            },
        },
        'player_formula': '(cont_o_rebs / o_rebounds) * 100',
        'team_formula': '(cont_o_rebs / o_rebounds) * 100',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'cont_dreb_pct': {
        'stat_category': 'tracking',
        'display_name': 'CDR%',
        'description': 'Contested defensive rebound % (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'CDR',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'cont_d_rebs',
                'team_formula': 'cont_d_rebs',
                'opponents_formula': None,
            },
        },
        'player_formula': '(cont_d_rebs / d_rebounds) * 100',
        'team_formula': '(cont_d_rebs / d_rebounds) * 100',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'putbacks': {
        'stat_category': 'tracking',
        'display_name': 'PBS',
        'description': 'Putbacks per offensive rebound % (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'putbacks',
        'team_formula': 'putbacks',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'def_close_2fga': {
        'stat_category': 'tracking',
        'display_name': 'DC2A',
        'description': 'Defended close two-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'd_close_2fga',
        'team_formula': 'd_close_2fga',
        'opponents_formula': None,
        'minimum_width': 31,
    },
    
    'points_per_def_close_2fga': {
        'stat_category': 'tracking',
        'display_name': 'PDC2',
        'description': 'Points allowed per defended close two',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2 * (d_close_2fgm / d_close_2fga)',
        'team_formula': '2 * (d_close_2fgm / d_close_2fga)',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'def_long_2fga': {
        'stat_category': 'tracking',
        'display_name': 'DL2A',
        'description': 'Defended long two-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'd_2fga - d_close_2fga',
        'team_formula': None,
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'points_per_def_long_2fga': {
        'stat_category': 'tracking',
        'display_name': 'PDL2',
        'description': 'Points allowed per defended long two',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2 * ((d_2fgm - d_close_2fgm) / (d_2fga - d_close_2fga))',
        'team_formula': '2 * ((d_2fgm - d_close_2fgm) / (d_2fga - d_close_2fga))',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'def_3fga': {
        'stat_category': 'tracking',
        'display_name': 'D3A',
        'description': 'Defended three-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'd_3fga',
        'team_formula': 'd_3fga',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'points_per_def_3fga': {
        'stat_category': 'tracking',
        'display_name': 'PD3',
        'description': 'Points allowed per defended three',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '3 * (d_3fgm / d_3fga)',
        'team_formula': '3 * (d_3fgm / d_3fga)',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'real_def_pct': {
        'stat_category': 'tracking',
        'display_name': 'RD%',
        'description': 'Real defensive FG% (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'player_formula': 'real_d_fg_pct_x1000 / 10',
        'team_formula': 'real_d_fg_pct_x1000 / 10',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'real_def_close_2_pct': {
        'stat_category': 'tracking',
        'display_name': 'RDC2%',
        'description': 'Real defensive close two FG% +/- (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'player_formula': 'real_d_close_2fg_pct_x1000 / 10',
        'team_formula': 'real_d_close_2fg_pct_x1000 / 10',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'real_def_2fg_pct': {
        'stat_category': 'tracking',
        'display_name': 'RD2%',
        'description': 'Real defensive 2pt FG% +/- (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'player_formula': 'real_d_2fg_pct_x1000 / 10',
        'team_formula': 'real_d_2fg_pct_x1000 / 10',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'real_def_3fg_pct': {
        'stat_category': 'tracking',
        'display_name': 'RD3%',
        'description': 'Real defensive 3pt FG% +/- (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'player_formula': 'real_d_3fg_pct_x1000 / 10',
        'team_formula': 'real_d_3fg_pct_x1000 / 10',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'blocks': {
        'stat_category': 'basic',
        'display_name': 'Blk',
        'description': 'Blocks',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'blocks',
        'team_formula': 'blocks',
        'opponents_formula': 'opp_blocks',
        'minimum_width': 'auto',
    },
    
    'contests': {
        'stat_category': 'hustle',
        'display_name': 'Cont',
        'description': 'Shot contests (hustle)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'contests',
        'team_formula': 'contests',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'steals_plus_charges': {
        'stat_category': 'basic',
        'display_name': 'ST+C',
        'description': 'steals plus charges drawn',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'steals + charges_drawn',
        'team_formula': 'steals + charges_drawn',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'deflections': {
        'stat_category': 'hustle',
        'display_name': 'DFLS',
        'description': 'Deflections (hustle)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'deflections',
        'team_formula': 'deflections',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'fouls': {
        'stat_category': 'basic',
        'display_name': 'Fls',
        'description': 'Personal fouls',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'fouls',
        'team_formula': 'fouls',
        'opponents_formula': 'opp_fouls',
        'minimum_width': 'auto',
    },
    
        'off_distance': {
        'stat_category': 'tracking',
        'display_name': 'ODST',
        'description': 'Offensive distance traveled in miles (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'movement',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'o_dist_x10 / 10',
        'team_formula': None,
        'opponents_formula': None,
        'minimum_width': 31,
    },
    
    'def_distance': {
        'stat_category': 'tracking',
        'display_name': 'DDST',
        'description': 'Defensive distance traveled in miles (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'movement',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'd_dist_x10 / 10',
        'team_formula': None,
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'o_rating': {
        'stat_category': 'basic',
        'display_name': 'ORT',
        'description': 'Offensive rating per 100 possessions',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'onoff',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'o_rating_x10 / 10',
        'team_formula': 'o_rating_x10 / 10',
        'opponents_formula': None,
        'minimum_width': 39,
    },
    
    'd_rating': {
        'stat_category': 'basic',
        'display_name': 'DRT',
        'description': 'Defensive rating per 100 possessions',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'onoff',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'd_rating_x10 / 10',
        'team_formula': 'd_rating_x10 / 10',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'net_off_o_rating': {
        'stat_category': 'basic',
        'display_name': 'NOOO',
        'description': 'Net Offensive on/off Team Rating',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'onoff',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '(o_rating_x10 / 10) - (off_o_rating_x10 / 10)',
        'team_formula': None,
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'net_off_d_rating': {
        'stat_category': 'basic',
        'display_name': 'NDOO',
        'description': 'Net Defensive on/off Team Rating',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'onoff',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '(d_rating_x10 / 10) - (off_d_rating_x10 / 10)',
        'team_formula': None,
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    # ========================================================================
    # IDENTITY SECTION
    # ========================================================================
    
    'nba_id': {
        'stat_category': 'none',
        'display_name': 'NBA ID',
        'description': 'NBA.com player/team ID',
        'section': ['identity'],
        'subsection': None,
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'player_id',
        'team_formula': 'team_id',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
}
