"""
THE GLASS NCAA - Display Configuration
Single source of truth for all display logic, calculations, formatting, and percentiles.
Mirrors config/nba_sheets.py for NCAA D1 basketball.

Key differences from NBA:
- 40-minute games (not 48)
- Per 40 Min mode (not Per 36)
- No tracking/hustle stats (no advanced toggle)
- No age column (birthdate always null)
- Conference column in player info
- Wins/Losses/Win% on teams sheet
- abbr instead of team_abbr, institution instead of team_name
- season column instead of year
"""

import os

from config.sheets import (  # noqa: F401 — re-exported
    COLORS, COLOR_THRESHOLDS, SHEET_FORMATTING,
    SECTION_CONFIG, SECTIONS, COLUMN_DEFAULTS,
)

# ============================================================================
# GOOGLE SHEETS CONFIGURATION
# ============================================================================

GOOGLE_SHEETS_CONFIG = {
    'credentials_file': os.getenv('GOOGLE_CREDENTIALS_FILE'),
    'spreadsheet_id': os.getenv('NCAA_SPREADSHEET_ID'),
    'spreadsheet_name': os.getenv('NCAA_SPREADSHEET_NAME', 'The Glass NCAA'),
    'scopes': [
        'https://www.googleapis.com/auth/spreadsheets',
        'https://www.googleapis.com/auth/drive'
    ],
}

# ============================================================================
# API CONFIGURATION (shared with NBA)
# ============================================================================

API_CONFIG = {
    'host': os.getenv('API_HOST', '0.0.0.0'),
    'port': int(os.getenv('API_PORT', '5000')),
    'debug': os.getenv('API_DEBUG', 'False').lower() == 'true',
    'cors_enabled': True,
}

SERVER_CONFIG = {
    'production_host': os.getenv('PRODUCTION_HOST', ''),
    'production_port': int(os.getenv('PRODUCTION_PORT', '5000')),
    'ssh_user': os.getenv('SSH_USER', ''),
    'remote_dir': os.getenv('REMOTE_DIR', ''),
    'systemd_service': os.getenv('SYSTEMD_SERVICE', 'flask-api'),
}

# ============================================================================
# STAT CALCULATION CONSTANTS
# ============================================================================

STAT_CONSTANTS = {
    'game_length_minutes': 40.0,        # NCAA game length (40 min, not 48)
    'default_per_minutes': 48.0,        # Per 48 Min (standardized across leagues)
    'default_per_possessions': 100.0,   # Default possessions for per-possession stats
    'cache_ttl_seconds': 300,           # API response cache TTL
}

# ============================================================================
# STAT MODE CONFIGURATION
# ============================================================================

STAT_MODES = ['per_100', 'per_game', 'per_48']
DEFAULT_STAT_MODE = 'per_100'

# ============================================================================
# SECTION AND SUBSECTION DEFINITIONS
# ============================================================================

# SECTION_CONFIG and SECTIONS — imported from config.sheets

# Stat subsections — no movement or onoff for NCAA
SUBSECTIONS = [
    'rates',
    'scoring',
    'ball_management',
    'rebounding',
    'defense',
    'opponent',
    'efficiency',
]

SUBSECTION_DISPLAY_NAMES = {
    'rates': 'Rates',
    'scoring': 'Scoring',
    'ball_management': 'Ball Management',
    'rebounding': 'Rebounding',
    'defense': 'Defense',
    'opponent': 'Opponent',
    'efficiency': 'Efficiency',
}

# SECTIONS — imported from config.sheets


# ============================================================================
# COLORS & PERCENTILES — imported from config.sheets
# ============================================================================


# ============================================================================
# SHEET FORMATTING CONFIG — imported from config.sheets
# ============================================================================

# ============================================================================
# SHEETS_COLUMNS - Master dictionary for all display columns
# ============================================================================

SHEETS_COLUMNS = {

    'names': {
        'stat_category': 'none',
        'display_name': 'Names',
        'description': 'player name / team name',
        'section': ['entities'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'name',
        'team_formula': 'TEAM',
        'opponents_formula': 'OPPONENTS',
        'minimum_width': 'auto',
    },

    'team': {
        'stat_category': 'none',
        'display_name': 'Tm',
        'description': 'team abbreviation',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_players'],
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'abbr',
        'team_formula': None,
        'opponents_formula': None,
        'minimum_width': 35,
    },

    'jersey': {
        'stat_category': 'none',
        'display_name': '#',
        'description': 'jersey number',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'jersey_number',
        'team_formula': None,
        'opponents_formula': None,
        'minimum_width': 20,
    },

    'experience': {
        'stat_category': 'none',
        'display_name': 'Exp',
        'description': 'years of college experience',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'years_experience',
        'team_formula': 'years_experience',
        'opponents_formula': None,
        'minimum_width': 32,
    },

    'conference': {
        'stat_category': 'none',
        'display_name': 'Conf',
        'description': 'conference',
        'section': ['player_info'],
        'subsection': None,
        'sheets': [],
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'conference',
        'team_formula': 'conference',
        'opponents_formula': None,
        'minimum_width': 45,
    },

    'height': {
        'stat_category': 'none',
        'display_name': 'Ht',
        'description': 'height',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'height',
        'decimal_places': 1,
        'player_formula': 'height_inches',
        'team_formula': 'height_inches',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },

    'weight': {
        'stat_category': 'none',
        'display_name': 'Wt',
        'description': 'weight',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'weight_lbs',
        'team_formula': 'weight_lbs',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },

    'wingspan': {
        'stat_category': 'none',
        'display_name': 'WS',
        'description': 'wingspan',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': False,
        'editable': True,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'height',
        'decimal_places': 1,
        'player_formula': 'wingspan_inches',
        'team_formula': 'wingspan_inches',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },

    'hand': {
        'stat_category': 'none',
        'display_name': '🖐️',
        'description': 'handedness',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': True,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'hand',
        'team_formula': None,
        'opponents_formula': None,
        'minimum_width': 20,
    },

    'notes': {
        'stat_category': 'none',
        'display_name': 'Notes',
        'description': 'Scouting notes (editable)',
        'section': ['analysis'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': True,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'notes',
        'team_formula': 'notes',
        'opponents_formula': None,
        'minimum_width': 500,
    },

    'years': {
        'stat_category': 'none',
        'display_name': 'Yrs',
        'description': 'Number of seasons in range',
        'section': ['historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'nullable': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'season',
        'team_formula': 'season',
        'opponents_formula': None,
        'minimum_width': 30,
    },

    'games': {
        'stat_category': 'none',
        'display_name': 'GMS',
        'description': 'Games played',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'nullable': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'games',
        'team_formula': 'games',
        'opponents_formula': None,
        'minimum_width': 30,
    },

    'minutes': {
        'stat_category': 'none',
        'display_name': 'Min',
        'description': 'Minutes played',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': 'per_game_only',
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'minutes_x10 / 10',
        'team_formula': 'minutes_x10 / 10',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },

    'pace': {
        'stat_category': 'basic',
        'display_name': 'Pace',
        'description': 'Possessions per 40 minutes',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '(40 / (minutes_x10 / 10)) * possessions',
        'team_formula': '(40 / (minutes_x10 / 10)) * possessions',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },

    'wins': {
        'stat_category': 'basic',
        'display_name': 'W',
        'description': 'Wins',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'sheets': ['all_teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': None,
        'team_formula': 'wins',
        'opponents_formula': None,
        'minimum_width': 30,
    },

    'losses': {
        'stat_category': 'basic',
        'display_name': 'L',
        'description': 'Losses',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'sheets': ['all_teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': None,
        'team_formula': 'losses',
        'opponents_formula': None,
        'minimum_width': 30,
    },

    'points': {
        'stat_category': 'basic',
        'display_name': 'PTS',
        'description': 'Total points scored',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '(2fgm * 2) + (3fgm * 3) + ftm',
        'team_formula': '(2fgm * 2) + (3fgm * 3) + ftm',
        'opponents_formula': '(opp_2fgm * 2) + (opp_3fgm * 3) + opp_ftm',
        'minimum_width': 35,
    },

    'true_points_per_shot_attempt': {
        'stat_category': 'basic',
        'display_name': 'TPS',
        'description': 'Points per true shot attempt (2FGA + 3FGA + 0.44*FTA)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '((2fgm * 2) + (3fgm * 3) + ftm) / (2fga + 3fga + 0.44 * fta)',
        'team_formula': '((2fgm * 2) + (3fgm * 3) + ftm) / (2fga + 3fga + 0.44 * fta)',
        'opponents_formula': '((opp_2fgm * 2) + (opp_3fgm * 3) + opp_ftm) / (opp_2fga + opp_3fga + 0.44 * opp_fta)',
        'minimum_width': 'auto',
    },

    '2fga': {
        'stat_category': 'basic',
        'display_name': '2A',
        'description': 'Two-point field goal attempts',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '2fga',
        'team_formula': '2fga',
        'opponents_formula': 'opp_2fga',
        'minimum_width': 'auto',
    },

    'Points_Per_Two_attempt': {
        'stat_category': 'basic',
        'display_name': 'P2',
        'description': 'Points per two-point attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2 * (2fgm / 2fga)',
        'team_formula': '2 * (2fgm / 2fga)',
        'opponents_formula': '2 * (opp_2fgm / opp_2fga)',
        'minimum_width': 'auto',
    },

    '3fga': {
        'stat_category': 'basic',
        'display_name': '3A',
        'description': 'Three-point field goal attempts',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '3fga',
        'team_formula': '3fga',
        'opponents_formula': 'opp_3fga',
        'minimum_width': 'auto',
    },

    'Points_Per_Three_attempt': {
        'stat_category': 'basic',
        'display_name': 'P3',
        'description': 'Points per three-point attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '3 * (3fgm / 3fga)',
        'team_formula': '3 * (3fgm / 3fga)',
        'opponents_formula': '3 * (opp_3fgm / opp_3fga)',
        'minimum_width': 'auto',
    },

    'free_throw_rate': {
        'stat_category': 'basic',
        'display_name': 'FTR',
        'description': 'Free throw attempts per field goal attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 2,
        'mode_overrides': {
            'totals': {
                'display_name': 'FTA',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'fta',
                'team_formula': 'fta',
                'opponents_formula': 'opp_fta',
            },
        },
        'player_formula': 'fta / (2fga + 3fga)',
        'team_formula': 'fta / (2fga + 3fga)',
        'opponents_formula': 'opp_fta / (opp_2fga + opp_3fga)',
        'minimum_width': 'auto',
    },

    'points_per_ft': {
        'stat_category': 'basic',
        'display_name': 'PFT',
        'description': 'Points per free throw',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': 'ftm / fta',
        'team_formula': 'ftm / fta',
        'opponents_formula': 'opp_ftm / opp_fta',
        'minimum_width': 'auto',
    },

    'assists': {
        'stat_category': 'basic',
        'display_name': 'AST',
        'description': 'Assists',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'assists',
        'team_formula': 'assists',
        'opponents_formula': 'opp_assists',
        'minimum_width': 30,
    },

    'turnovers': {
        'stat_category': 'basic',
        'display_name': 'TOV',
        'description': 'Turnovers',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'turnovers',
        'team_formula': 'turnovers',
        'opponents_formula': 'opp_turnovers',
        'minimum_width': 'auto',
    },

    'oreb_pct': {
        'stat_category': 'basic',
        'display_name': 'OR%',
        'description': 'Offensive rebound percentage',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'OREB',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'o_rebounds',
                'team_formula': 'o_rebounds',
                'opponents_formula': 'opp_o_rebounds',
            },
        },
        'player_formula': 'o_rebound_pct_x1000 / 10000',
        'team_formula': 'o_rebound_pct_x1000 / 1000',
        'opponents_formula': None,
        'minimum_width': 30,
    },

    'dreb_pct': {
        'stat_category': 'basic',
        'display_name': 'DR%',
        'description': 'Defensive rebound percentage',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'DREB',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'd_rebounds',
                'team_formula': 'd_rebounds',
                'opponents_formula': 'opp_d_rebounds',
            },
        },
        'player_formula': 'd_rebound_pct_x1000 / 10',
        'team_formula': 'd_rebound_pct_x1000 / 10',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },

    'steals': {
        'stat_category': 'basic',
        'display_name': 'Stl',
        'description': 'Steals',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'steals',
        'team_formula': 'steals',
        'opponents_formula': 'opp_steals',
        'minimum_width': 'auto',
    },

    'blocks': {
        'stat_category': 'basic',
        'display_name': 'Blk',
        'description': 'Blocks',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'blocks',
        'team_formula': 'blocks',
        'opponents_formula': 'opp_blocks',
        'minimum_width': 'auto',
    },

    'fouls': {
        'stat_category': 'basic',
        'display_name': 'Fls',
        'description': 'Personal fouls',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'fouls',
        'team_formula': 'fouls',
        'opponents_formula': 'opp_fouls',
        'minimum_width': 'auto',
    },

    'o_rating': {
        'stat_category': 'basic',
        'display_name': 'ORT',
        'description': 'Offensive rating per 100 possessions',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'efficiency',
        'sheets': ['all_teams', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': None,
        'team_formula': 'o_rating_x10 / 10',
        'opponents_formula': None,
        'minimum_width': 39,
    },

    'd_rating': {
        'stat_category': 'basic',
        'display_name': 'DRT',
        'description': 'Defensive rating per 100 possessions',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'efficiency',
        'sheets': ['all_teams', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': None,
        'team_formula': 'd_rating_x10 / 10',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },

    'win_pct': {
        'stat_category': 'basic',
        'display_name': 'W%',
        'description': 'Win percentage',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'efficiency',
        'sheets': ['all_teams', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 3,
        'player_formula': None,
        'team_formula': 'wins / (wins + losses)',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },

    # ========================================================================
    # IDENTITY SECTION
    # ========================================================================

    'ncaa_id': {
        'stat_category': 'none',
        'display_name': 'NCAA ID',
        'description': 'NCAA player/team ID',
        'section': ['identity'],
        'subsection': None,
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'player_id',
        'team_formula': 'team_id',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
}
