"""
THE GLASS - Display Configuration
Single source of truth for all display logic, calculations, formatting, and percentiles.

This config drives:
- Sheet column generation (src/sheets.py)
- Stat calculations (lib/sheets.py)
- Percentile generation (auto-generated columns)
- Section organization (player_info, analysis, rates, scoring, distribution, rebounding, defense, onoff, identity)
"""

import os

# ============================================================================
# GOOGLE SHEETS CONFIGURATION
# ============================================================================

GOOGLE_SHEETS_CONFIG = {
    'credentials_file': os.getenv('GOOGLE_CREDENTIALS_FILE'),
    'spreadsheet_id': os.getenv('GOOGLE_SPREADSHEET_ID'),
    'spreadsheet_name': os.getenv('GOOGLE_SPREADSHEET_NAME'),
    'scopes': [
        'https://www.googleapis.com/auth/spreadsheets',
        'https://www.googleapis.com/auth/drive'
    ],
}

# ============================================================================
# API CONFIGURATION
# ============================================================================

API_CONFIG = {
    'host': os.getenv('API_HOST', '0.0.0.0'),
    'port': int(os.getenv('API_PORT', '5000')),
    'debug': os.getenv('API_DEBUG', 'False').lower() == 'true',
    'cors_enabled': True,
}

SERVER_CONFIG = {
    'production_host': os.getenv('PRODUCTION_HOST', ''),
    'production_port': int(os.getenv('PRODUCTION_PORT', '5000')),
    'ssh_user': os.getenv('SSH_USER', ''),
    'remote_dir': os.getenv('REMOTE_DIR', ''),
    'systemd_service': os.getenv('SYSTEMD_SERVICE', 'flask-api'),
}

# ============================================================================
# STAT CALCULATION CONSTANTS
# ============================================================================

STAT_CONSTANTS = {
    'game_length_minutes': 48.0,        # NBA game length
    'default_per_minutes': 36.0,        # Default minutes for per-minute stats
    'default_per_possessions': 100.0,   # Default possessions for per-possession stats
    'cache_ttl_seconds': 300,           # API response cache TTL
}

# ============================================================================
# SECTION AND SUBSECTION DEFINITIONS
# ============================================================================

# Section display configuration - defines how each section appears in sheets
SECTION_CONFIG = {
    'entities': {
        'display_name': 'Names',
    },
    'player_info': {
        'display_name': 'Player Info',
    },
    'analysis': {
        'display_name': 'Analysis',
    },
    'current_stats': {
        'display_name': 'Current Stats',
        'is_stats_section': True,
    },
    'historical_stats': {
        'display_name': 'Historical Stats',
        'is_stats_section': True,
    },
    'postseason_stats': {
        'display_name': 'Postseason Stats',
        'is_stats_section': True,
    },
    'identity': {
        'display_name': 'Identity',
    },
}

# Stat subsections - correspond to Row 2 subsection headers (within current_stats/historical_stats/postseason_stats)
SUBSECTIONS = [
    'rates',          # Games, Minutes, Possessions
    'scoring',        # Points, TS%, 2fg/3, Rim/Mid/3PT tracking, FT
    'distribution',   # Touches, Assists, Potential Assists, Turnovers
    'rebounding',     # OREB%, DREB%, Contested OREB/DREB%, Putbacks
    'movement',       # Offensive/Defensive distance traveled
    'defense',        # Defended shots, Steals, Deflections, Blocks, Contests, Charges, Fouls
    'onoff',          # Offensive/Defensive Rating, Off-court ratings
]

# Section order - determines left-to-right column layout in sheets
SECTIONS = [
    'entities',
    'player_info',
    'analysis',
    'current_stats',
    'historical_stats',
    'postseason_stats',
    'identity',
]


# ============================================================================
# COLORS & PERCENTILES
# ============================================================================

COLORS = {
    'red': {'red': 0.933, 'green': 0.294, 'blue': 0.169},
    'yellow': {'red': 0.988, 'green': 0.961, 'blue': 0.373},
    'green': {'red': 0.298, 'green': 0.733, 'blue': 0.090},
    'black': {'red': 0, 'green': 0, 'blue': 0},
    'white': {'red': 1, 'green': 1, 'blue': 1},
    'light_gray': {'red': 0.95, 'green': 0.95, 'blue': 0.95},
    'dark_gray': {'red': 67/255, 'green': 67/255, 'blue': 67/255},
}

COLOR_THRESHOLDS = {
    'low': 0,    # 0% = pure red
    'mid': 50,   # 50% = pure yellow
    'high': 100, # 100% = pure green
}

# ============================================================================
# SHEETS_COLUMNS - Master dictionary for all display columns
# ============================================================================

SHEETS_COLUMNS = {

    'names': {
        'display_name': 'Names',
        'section': ['entities'],
        'subsection': None,
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'name',
        'team_formula': 'Team',
        'opponents_formula': 'Opponents',
    },
    
    'team': {
        'display_name': 'Tm',
        'section': ['player_info'],
        'subsection': None,
        'sheets': 'nba',
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'team_abbr',
        'team_formula': None,
        'opponents_formula': None,
    },
    
    'jersey': {
        'display_name': '#',
        'section': ['player_info'],
        'subsection': None,
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'jersey_number',
        'team_formula': None,
        'opponents_formula': None,
    },
    
    'experience': {
        'display_name': 'Exp',
        'section': ['player_info'],
        'subsection': None,
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'years_experience',
        'team_formula': 'years_experience',
        'opponents_formula': None,
    },
    
    'age': {
        'display_name': 'Age',
        'section': ['player_info'],
        'subsection': None,
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'age',
        'team_formula': 'age',
        'opponents_formula': None,
    },
    
    'height': {
        'display_name': 'Ht',
        'section': ['player_info'],
        'subsection': None,
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'height',
        'decimal_places': 1,
        'player_formula': 'height_inches',
        'team_formula': 'height_inches',
        'opponents_formula': None,
    },
    
    'weight': {
        'display_name': 'Wt',
        'section': ['player_info'],
        'subsection': None,
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'weight_lbs',
        'team_formula': 'weight_lbs',
        'opponents_formula': None,
    },
    
    'wingspan': {
        'display_name': 'WS',
        'section': ['player_info'],
        'subsection': None,
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': False,
        'editable': True,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'height',
        'decimal_places': 1,
        'player_formula': 'wingspan_inches',
        'team_formula': 'wingspan_inches',
        'opponents_formula': None,
    },
    
    'hand': {
        'display_name': '🖐️',
        'section': ['player_info'],
        'subsection': None,
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': True,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'hand',
        'team_formula': None,
        'opponents_formula': None,
    },
    
    'notes': {
        'display_name': 'Notes',
        'section': ['analysis'],
        'subsection': None,
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': True,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'notes',
        'team_formula': 'notes',
        'opponents_formula': None,
    },

    'years': {
        'display_name': 'Yrs',
        'section': ['historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'year',
        'team_formula': 'year',
        'opponents_formula': None,
    },
        
    'games': {
        'display_name': 'GMS',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'games',
        'team_formula': 'games',
        'opponents_formula': None,
    },
    
    'minutes': {
        'display_name': 'Min',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': 'per_game_only',
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'minutes_x10 / 10',
        'team_formula': 'minutes_x10 / 10',
        'opponents_formula': None,
    },
    
    'pace': {
        'display_name': 'Pace',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'possessions / minutes',
        'team_formula': 'possessions / minutes',
        'opponents_formula': None,
    },
    
    'points': {
        'display_name': 'PTS',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '(2fgm * 2) + (3fgm * 3) + ftm',
        'team_formula': '(2fgm * 2) + (3fgm * 3) + ftm',
        'opponents_formula': '(opp_2fgm * 2) + (opp_3fgm * 3) + opp_ftm',
    },
    
    'true_points_per_shot_attempt': {
        'display_name': 'TPS',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': 'points / (2fga + 3fga + 0.44 * fta)',
        'team_formula': 'points / (2fga + 3fga + 0.44 * fta)',
        'opponents_formula': 'points / (opp_2fga + opp_3fga + 0.44 * opp_fta)',
    },
    
    '2fga': {
        'display_name': '2A',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'basic',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '2fga',
        'team_formula': '2fga',
        'opponents_formula': 'opp_2fga',
    },
    
    'Points_Per_Two_attempt': {
        'display_name': 'P2',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'basic',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2 * (2fgm / 2fga)',
        'team_formula': '2 * (2fgm / 2fga)',
        'opponents_formula': '2 * (opp_2fgm / opp_2fga)',
    },
    
    '3fga': {
        'display_name': '3A',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'basic',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '3fga',
        'team_formula': '3fga',
        'opponents_formula': 'opp_3fga',
    },
    
    'Points_Per_Three_attempt': {
        'display_name': 'P3',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'basic',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '3 * (3fgm / 3fga)',
        'team_formula': '3 * (3fgm / 3fga)',
        'opponents_formula': '3 * (opp_3fgm / opp_3fga)',
    },
    
    'cont_close_2fga': {
        'display_name': 'CC2A',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'cont_close_2fga',
        'team_formula': 'cont_close_2fga',
        'opponents_formula': None,
    },
    
    'Points_Per_cont_close_2fga': {
        'display_name': 'PCC2',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2 * (cont_close_2fgm / cont_close_2fga)',
        'team_formula': '2 * (cont_close_2fgm / cont_close_2fga)',
        'opponents_formula': None,
    },
    
    'open_close_2fga': {
        'display_name': 'OC2A',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'open_close_2fga',
        'team_formula': 'open_close_2fga',
        'opponents_formula': None,
    },
    
    'Points_Per_open_close_2fga': {
        'display_name': 'POC2',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2 * (open_close_2fgm / open_close_2fga)',
        'team_formula': '2 * (open_close_2fgm / open_close_2fga)',
        'opponents_formula': None,
    },
    
    'cont_long_2fga': {
        'display_name': 'CL2A',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'cont_2fga - cont_close_2fga',
        'team_formula': 'cont_2fga - cont_close_2fga',
        'opponents_formula': None,
    },
    
    'points_per_cont_long_2fga': {
        'display_name': 'PCL2',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2 * ((cont_2fgm - cont_close_2fgm) / (cont_2fga - cont_close_2fga))',
        'team_formula': '2 * ((cont_2fgm - cont_close_2fgm) / (cont_2fga - cont_close_2fga))',
        'opponents_formula': None,
    },
    
    'open_long_2fga': {
        'display_name': 'OL2A',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'open_2fga - open_close_2fga',
        'team_formula': 'open_2fga - open_close_2fga',
        'opponents_formula': None,
    },
    
    'points_per_open_long_2fga': {
        'display_name': 'POL2',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2* ((open_2fgm - open_close_2fgm) / (open_2fga - open_close_2fga))',
        'team_formula': '2* ((open_2fgm - open_close_2fgm) / (open_2fga - open_close_2fga))',
        'opponents_formula': None,
    },
    
    'cont_3fga': {
        'display_name': 'C3A',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'cont_3fga',
        'team_formula': 'cont_3fga',
        'opponents_formula': None,
    },
    
    'points_per_cont_3fga': {
        'display_name': 'PC3',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '3 * (cont_3fgm / cont_3fga)',
        'team_formula': '3 * (cont_3fgm / cont_3fga)',
        'opponents_formula': None,
    },
    
    'open_3fga': {
        'display_name': 'O3A',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'open_3fga',
        'team_formula': 'open_3fga',
        'opponents_formula': None,
    },
    
    'points_per_open_3fga': {
        'display_name': 'PO3',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '3 * (open_3fgm / open_3fga)',
        'team_formula': '3 * (open_3fgm / open_3fga)',
        'opponents_formula': None,
    },
    
    'free_throw_rate': {
        'display_name': 'FTR',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'FTA',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'fta',
                'team_formula': 'fta',
                'opponents_formula': 'opp_fta',
            },
        },
        'player_formula': 'fta / (2fga + 3fga)',
        'team_formula': 'fta / (2fga + 3fga)',
        'opponents_formula': 'opp_fta / (opp_2fga + opp_3fga)',
    },
    
    'points_per_ft_trip': {
        'display_name': 'PFTT',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': 'ftm / (.44 * fta)',
        'team_formula': 'ftm / (.44 * fta)',
        'opponents_formula': 'opp_ftm / (.44 * opp_fta)',
    },
    
    'assists': {
        'display_name': 'AST',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'distribution',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'assists',
        'team_formula': 'assists',
        'opponents_formula': 'opp_assists',
    },
    
    'potential_assists': {
        'display_name': 'PAST',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'distribution',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'pot_assists',
        'team_formula': 'pot_assists',
        'opponents_formula': None,
    },
    
    'secondary_assists': {
        'display_name': '2AST',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'distribution',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'sec_assists',
        'team_formula': 'sec_assists',
        'opponents_formula': None,
    },
    
    'passes': {
        'display_name': 'Pass',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'distribution',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'passes',
        'team_formula': 'passes',
        'opponents_formula': None,
    },
    
    'touches': {
        'display_name': 'Tou',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'distribution',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'touches',
        'team_formula': 'touches',
        'opponents_formula': None,
    },
    
    'seconds_per_touch': {
        'display_name': 'SPT',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'distribution',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'time_on_ball / touches',
        'team_formula': 'time_on_ball / touches',
        'opponents_formula': None,
    },
    
    'dribbles_per_touch': {
        'display_name': 'DPT',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'distribution',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'dribbles / touches',
        'team_formula': 'dribbles / touches',
        'opponents_formula': None,
    },
    
    'turnover_pct': {
        'display_name': 'TOV%',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'distribution',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'TOV',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'turnovers',
                'team_formula': 'turnovers',
                'opponents_formula': 'opp_turnovers',
            },
        },
        'player_formula': '(turnovers / possessions) * 100',
        'team_formula': '(turnovers / possessions) * 100',
        'opponents_formula': '(opp_turnovers / possessions) * 100',
    },
    
    'oreb_pct': {
        'display_name': 'OR%',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'OREB',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'o_rebounds',
                'team_formula': 'o_rebounds',
                'opponents_formula': 'opp_o_rebounds',
            },
        },
        'player_formula': 'o_rebound_pct_x1000 / 10',
        'team_formula': 'o_rebound_pct_x1000 / 10',
        'opponents_formula': 'opp_o_rebound_pct_x1000 / 10',
    },
    
    'dreb_pct': {
        'display_name': 'DR%',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'DRS',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'd_rebounds',
                'team_formula': 'd_rebounds',
                'opponents_formula': 'opp_d_rebounds',
            },
        },
        'player_formula': 'd_rebound_pct_x1000 / 10',
        'team_formula': 'd_rebound_pct_x1000 / 10',
        'opponents_formula': 'opp_d_rebound_pct_x1000 / 10',
    },
    
    'cont_oreb_pct': {
        'display_name': 'COR%',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'COR',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'cont_o_rebs',
                'team_formula': 'cont_o_rebs',
                'opponents_formula': None,
            },
        },
        'player_formula': '(cont_o_rebs / o_rebounds) * 100',
        'team_formula': '(cont_o_rebs / o_rebounds) * 100',
        'opponents_formula': None,
    },
    
    'cont_dreb_pct': {
        'display_name': 'CDR%',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'CDR',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'cont_d_rebs',
                'team_formula': 'cont_d_rebs',
                'opponents_formula': None,
            },
        },
        'player_formula': '(cont_d_rebs / d_rebounds) * 100',
        'team_formula': '(cont_d_rebs / d_rebounds) * 100',
        'opponents_formula': None,
    },
    
    'putback_pct': {
        'display_name': 'PB%',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'player_formula': '(putbacks / o_rebounds) * 100',
        'team_formula': '(putbacks / o_rebounds) * 100',
        'opponents_formula': None,
    },
    
    'off_distance': {
        'display_name': 'Off Dist',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'movement',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'o_dist_x10 / 10',
        'team_formula': None,
        'opponents_formula': None,
    },
    
    'def_distance': {
        'display_name': 'Def Dist',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'movement',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'd_dist_x10 / 10',
        'team_formula': None,
        'opponents_formula': None,
    },
    
    'def_close_2fga': {
        'display_name': 'DC2A',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'd_close_2fga',
        'team_formula': 'd_close_2fga',
        'opponents_formula': None,
    },
    
    'points_per_def_close_2fga': {
        'display_name': 'PDC2',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2 * (d_close_2fgm / d_close_2fga)',
        'team_formula': '2 * (d_close_2fgm / d_close_2fga)',
        'opponents_formula': None,
    },
    
    'def_long_2fga': {
        'display_name': 'DL2A',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'd_2fga - d_close_2fga',
        'team_formula': None,
        'opponents_formula': None,
    },
    
    'points_per_def_long_2fga': {
        'display_name': 'PDL2',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2 * ((d_2fgm - d_close_2fgm) / (d_2fga - d_close_2fga))',
        'team_formula': '2 * ((d_2fgm - d_close_2fgm) / (d_2fga - d_close_2fga))',
        'opponents_formula': None,
    },
    
    'def_3fga': {
        'display_name': 'D3A',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'd_3fga',
        'team_formula': 'd_3fga',
        'opponents_formula': None,
    },
    
    'points_per_def_3fga': {
        'display_name': 'PD3',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '3 * (d_3fgm / d_3fga)',
        'team_formula': '3 * (d_3fgm / d_3fga)',
        'opponents_formula': None,
    },
    
    'real_def_pct': {
        'display_name': 'RD%',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'player_formula': 'real_d_fg_pct_x1000 / 1000',
        'team_formula': 'real_d_fg_pct_x1000 / 1000',
        'opponents_formula': None,
    },
    
    'block_pct': {
        'display_name': 'Blk%',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'BLK',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'blocks',
                'team_formula': 'blocks',
                'opponents_formula': 'opp_blocks',
            },
        },
        'player_formula': 'blocks / contests',
        'team_formula': 'blocks / (opp_2fga + opp_3fga)',
        'opponents_formula': 'opp_blocks / (2fga + 3fga)',
    },
    
    'contests': {
        'display_name': 'Contests',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'contests',
        'team_formula': 'contests',
        'opponents_formula': 'opp_contests',
    },
    
    'steals_plus_charges': {
        'display_name': 'TOVF',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'steals + charges',
        'team_formula': 'steals + charges',
        'opponents_formula': None,
    },
    
    'deflections': {
        'display_name': 'Deflections',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'deflections',
        'team_formula': 'deflections',
        'opponents_formula': 'opp_deflections',
    },
    
    'fouls': {
        'display_name': 'Fouls',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'fouls',
        'team_formula': 'fouls',
        'opponents_formula': 'opp_fouls',
    },
    
    'off_rating': {
        'display_name': 'ORT',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'onoff',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'off_rating_x10 / 10',
        'team_formula': 'off_rating_x10 / 10',
        'opponents_formula': None,
    },
    
    'def_rating': {
        'display_name': 'DRT',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'onoff',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'def_rating_x10 / 10',
        'team_formula': 'def_rating_x10 / 10',
        'opponents_formula': None,
    },
    
    'off_onoff': {
        'display_name': 'OO/O',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'onoff',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'off_onoff_x10 / 10',
        'team_formula': None,
        'opponents_formula': None,
    },
    
    'def_onoff': {
        'display_name': 'DO/O',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'onoff',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'def_onoff_x10 / 10',
        'team_formula': None,
        'opponents_formula': None,
    },
    
    # ========================================================================
    # IDENTITY SECTION
    # ========================================================================
    
    'nba_id': {
        'display_name': 'NBA ID',
        'section': ['identity'],
        'subsection': None,
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'player_id',
        'team_formula': 'team_id',
        'opponents_formula': None,
    },
}
