"""
THE GLASS - Display Configuration
Single source of truth for all display logic, calculations, formatting, and percentiles.

This config drives:
- Sheet column generation (src/sheets.py)
- Stat calculations (lib/sheets.py)
- Percentile generation (auto-generated columns)
- Section organization (player_info, analysis, rates, scoring, ball_management, rebounding, defense, onoff, identity)
"""

import os

# ============================================================================
# GOOGLE SHEETS CONFIGURATION
# ============================================================================

GOOGLE_SHEETS_CONFIG = {
    'credentials_file': os.getenv('GOOGLE_CREDENTIALS_FILE'),
    'spreadsheet_id': os.getenv('GOOGLE_SPREADSHEET_ID'),
    'spreadsheet_name': os.getenv('GOOGLE_SPREADSHEET_NAME'),
    'scopes': [
        'https://www.googleapis.com/auth/spreadsheets',
        'https://www.googleapis.com/auth/drive'
    ],
}

# ============================================================================
# API CONFIGURATION
# ============================================================================

API_CONFIG = {
    'host': os.getenv('API_HOST', '0.0.0.0'),
    'port': int(os.getenv('API_PORT', '5000')),
    'debug': os.getenv('API_DEBUG', 'False').lower() == 'true',
    'cors_enabled': True,
}

SERVER_CONFIG = {
    'production_host': os.getenv('PRODUCTION_HOST', ''),
    'production_port': int(os.getenv('PRODUCTION_PORT', '5000')),
    'ssh_user': os.getenv('SSH_USER', ''),
    'remote_dir': os.getenv('REMOTE_DIR', ''),
    'systemd_service': os.getenv('SYSTEMD_SERVICE', 'flask-api'),
}

# ============================================================================
# STAT CALCULATION CONSTANTS
# ============================================================================

STAT_CONSTANTS = {
    'game_length_minutes': 48.0,        # NBA game length
    'default_per_minutes': 36.0,        # Default minutes for per-minute stats
    'default_per_possessions': 100.0,   # Default possessions for per-possession stats
    'cache_ttl_seconds': 300,           # API response cache TTL
}

# ============================================================================
# SECTION AND SUBSECTION DEFINITIONS
# ============================================================================

# Section display configuration - defines how each section appears in sheets
SECTION_CONFIG = {
    'entities': {
        'display_name': 'Names',
    },
    'player_info': {
        'display_name': 'Player Info',
    },
    'analysis': {
        'display_name': 'Analysis',
    },
    'current_stats': {
        'display_name': 'Current Stats',
        'is_stats_section': True,
    },
    'historical_stats': {
        'display_name': 'Historical Stats',
        'is_stats_section': True,
    },
    'postseason_stats': {
        'display_name': 'Postseason Stats',
        'is_stats_section': True,
    },
    'identity': {
        'display_name': 'Identity',
    },
}

# Stat subsections - correspond to Row 2 subsection headers (within current_stats/historical_stats/postseason_stats)
SUBSECTIONS = [
    'rates',          # Games, Minutes, Possessions
    'scoring',        # Points, TS%, 2fg/3, Rim/Mid/3PT tracking, FT
    'ball_management',   # Touches, Assists, Potential Assists, Turnovers
    'rebounding',     # OREB%, DREB%, Contested OREB/DREB%, Putbacks
    'movement',       # Offensive/Defensive distance traveled
    'defense',        # Defended shots, Steals, Deflections, Blocks, Contests, Charges, Fouls
    'onoff',          # Offensive/Defensive Rating, Off-court ratings
]

# Section order - determines left-to-right column layout in sheets
SECTIONS = [
    'entities',
    'player_info',
    'analysis',
    'current_stats',
    'historical_stats',
    'postseason_stats',
    'identity',
]


# ============================================================================
# COLORS & PERCENTILES
# ============================================================================

COLORS = {
    'red': {'red': 0.933, 'green': 0.294, 'blue': 0.169},
    'yellow': {'red': 0.988, 'green': 0.961, 'blue': 0.373},
    'green': {'red': 0.298, 'green': 0.733, 'blue': 0.090},
    'black': {'red': 0, 'green': 0, 'blue': 0},
    'white': {'red': 1, 'green': 1, 'blue': 1},
    'light_gray': {'red': 0.95, 'green': 0.95, 'blue': 0.95},
    'dark_gray': {'red': 67/255, 'green': 67/255, 'blue': 67/255},
    'row_alt': {'red': 0.94, 'green': 0.94, 'blue': 0.94},
}

COLOR_THRESHOLDS = {
    'low': 0,    # 0% = pure red
    'mid': 50,   # 50% = pure yellow
    'high': 100, # 100% = pure green
}


# ============================================================================
# SHEET FORMATTING CONFIG
# ============================================================================

SHEET_FORMATTING = {
    # Fonts
    'header_font': 'Staatliches',
    'data_font': 'Sofia Sans',

    # Font sizes
    'section_header_size': 12,
    'team_name_size': 15,          # Team name merged into section header row
    'subsection_header_size': 12,
    'column_header_size': 10,
    'data_size': 10,

    # Header styling
    'header_bg': 'black',
    'header_fg': 'white',

    # Data row alternating colors (uses addBanding so colors survive sorting)
    'row_even_bg': 'white',
    'row_odd_bg': 'row_alt',

    # Borders — all weight 2, white in header rows, black in data rows
    'border_weight': 2,
    'header_border_color': 'white',
    'data_border_color': 'black',

    # Alignment — all cells centered except overrides
    'default_h_align': 'CENTER',
    'default_v_align': 'MIDDLE',
    'left_align_columns': ['names', 'notes'],  # left-justified in data rows only
    'bold_columns': ['names'],                  # bold text in data rows

    # Overflow handling
    'wrap_strategy': 'CLIP',  # CLIP | WRAP | OVERFLOW_CELL

    # Default visibility
    'hide_advanced_columns': True,
    'hide_percentile_columns': True,
    'hide_subsection_row': True,
    'hide_identity_section': True,

    # Layout — 4 header rows
    # Row 0: Section headers (team name merged into entities section)
    # Row 1: Subsection headers (hidden by default)
    # Row 2: Column names
    # Row 3: Filter row (auto-filter dropdowns)
    'section_header_row': 0,
    'subsection_header_row': 1,
    'column_header_row': 2,
    'filter_row': 3,
    'data_start_row': 4,
    'header_row_count': 4,

    # Freeze
    'frozen_rows': 4,         # Freeze through filter row
    'frozen_cols': 1,         # Freeze Names column

    # Row sections (visual grouping in data area)
    'row_sections': ['current_players', 'team_opponent'],

    # Rate limiting
    'sync_delay_seconds': 3,  # Delay between team syncs to avoid 429
}

# ============================================================================
# SHEETS_COLUMNS - Master dictionary for all display columns
# ============================================================================

SHEETS_COLUMNS = {

    'names': {
        'stat_category': 'none',
        'display_name': 'Names',
        'description': 'Player name',
        'section': ['entities'],
        'subsection': None,
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'name',
        'team_formula': 'TEAM',
        'opponents_formula': 'OPPONENTS',
        'minimum_width': 'auto',
    },
    
    'team': {
        'stat_category': 'none',
        'display_name': 'Team',
        'description': 'Team abbreviation',
        'section': ['player_info'],
        'subsection': None,
        'sheets': 'players',
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'team_abbr',
        'team_formula': None,
        'opponents_formula': None,
        'minimum_width': 35,
    },
    
    'jersey': {
        'stat_category': 'none',
        'display_name': '#',
        'description': 'Jersey number',
        'section': ['player_info'],
        'subsection': None,
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'jersey_number',
        'team_formula': None,
        'opponents_formula': None,
        'minimum_width': 20,
    },
    
    'experience': {
        'stat_category': 'none',
        'display_name': 'Exp',
        'description': 'Years of NBA experience',
        'section': ['player_info'],
        'subsection': None,
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'years_experience',
        'team_formula': 'years_experience',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'age': {
        'stat_category': 'none',
        'display_name': 'Age',
        'description': 'Player age',
        'section': ['player_info'],
        'subsection': None,
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'age',
        'team_formula': 'age',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'height': {
        'stat_category': 'none',
        'display_name': 'Ht',
        'description': 'Height in feet and inches',
        'section': ['player_info'],
        'subsection': None,
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'height',
        'decimal_places': 1,
        'player_formula': 'height_inches',
        'team_formula': 'height_inches',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'weight': {
        'stat_category': 'none',
        'display_name': 'Wt',
        'description': 'Weight in pounds',
        'section': ['player_info'],
        'subsection': None,
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'weight_lbs',
        'team_formula': 'weight_lbs',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'wingspan': {
        'stat_category': 'none',
        'display_name': 'WS',
        'description': 'Wingspan in feet and inches (editable)',
        'section': ['player_info'],
        'subsection': None,
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': False,
        'editable': True,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'height',
        'decimal_places': 1,
        'player_formula': 'wingspan_inches',
        'team_formula': 'wingspan_inches',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'hand': {
        'stat_category': 'none',
        'display_name': '🖐️',
        'description': 'Dominant hand (editable)',
        'section': ['player_info'],
        'subsection': None,
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': True,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'hand',
        'team_formula': None,
        'opponents_formula': None,
        'minimum_width': 20,
    },
    
    'notes': {
        'stat_category': 'none',
        'display_name': 'Notes',
        'description': 'Scouting notes (editable)',
        'section': ['analysis'],
        'subsection': None,
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': True,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'notes',
        'team_formula': 'notes',
        'opponents_formula': None,
        'minimum_width': 500,
    },

    'years': {
        'stat_category': 'none',
        'display_name': 'Yrs',
        'description': 'Number of seasons in range',
        'section': ['historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'nullable': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'year',
        'team_formula': 'year',
        'opponents_formula': None,
        'minimum_width': 30,
    },
        
    'games': {
        'stat_category': 'none',
        'display_name': 'GMS',
        'description': 'Games played',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'sheets': 'both',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'nullable': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'games',
        'team_formula': 'games',
        'opponents_formula': None,
        'minimum_width': 30,
    },
    
    'minutes': {
        'stat_category': 'none',
        'display_name': 'Min',
        'description': 'Minutes played',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': 'per_game_only',
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'minutes_x10 / 10',
        'team_formula': 'minutes_x10 / 10',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'pace': {
        'stat_category': 'basic',
        'display_name': 'Pace',
        'description': 'Possessions per minute',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '(240 / (minutes_x10 / 10)) * possessions',
        'team_formula': '(240 / (minutes_x10 / 10)) * possessions',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'points': {
        'stat_category': 'basic',
        'display_name': 'PTS',
        'description': 'Total points scored',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '(2fgm * 2) + (3fgm * 3) + ftm',
        'team_formula': '(2fgm * 2) + (3fgm * 3) + ftm',
        'opponents_formula': '(opp_2fgm * 2) + (opp_3fgm * 3) + opp_ftm',
        'minimum_width': 30,
    },
    
    'true_points_per_shot_attempt': {
        'stat_category': 'basic',
        'display_name': 'TPS',
        'description': 'Points per true shot attempt (2FGA + 3FGA + 0.44*FTA)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '((2fgm * 2) + (3fgm * 3) + ftm) / (2fga + 3fga + 0.44 * fta)',
        'team_formula': '((2fgm * 2) + (3fgm * 3) + ftm) / (2fga + 3fga + 0.44 * fta)',
        'opponents_formula': '((opp_2fgm * 2) + (opp_3fgm * 3) + opp_ftm) / (opp_2fga + opp_3fga + 0.44 * opp_fta)',
        'minimum_width': 'auto',
    },
    
    '2fga': {
        'stat_category': 'basic',
        'display_name': '2A',
        'description': 'Two-point field goal attempts',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'basic',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '2fga',
        'team_formula': '2fga',
        'opponents_formula': 'opp_2fga',
        'minimum_width': 'auto',
    },
    
    'Points_Per_Two_attempt': {
        'stat_category': 'basic',
        'display_name': 'P2',
        'description': 'Points per two-point attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'basic',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2 * (2fgm / 2fga)',
        'team_formula': '2 * (2fgm / 2fga)',
        'opponents_formula': '2 * (opp_2fgm / opp_2fga)',
        'minimum_width': 'auto',
    },
    
    'cont_close_2fga': {
        'stat_category': 'tracking',
        'display_name': 'CC2A',
        'description': 'Contested close two-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'cont_close_2fga',
        'team_formula': 'cont_close_2fga',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'Points_Per_cont_close_2fga': {
        'stat_category': 'tracking',
        'display_name': 'PCC2',
        'description': 'Points per contested close two attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2 * (cont_close_2fgm / cont_close_2fga)',
        'team_formula': '2 * (cont_close_2fgm / cont_close_2fga)',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'open_close_2fga': {
        'stat_category': 'tracking',
        'display_name': 'OC2A',
        'description': 'Open close two-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'open_close_2fga',
        'team_formula': 'open_close_2fga',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'Points_Per_open_close_2fga': {
        'stat_category': 'tracking',
        'display_name': 'POC2',
        'description': 'Points per open close two attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2 * (open_close_2fgm / open_close_2fga)',
        'team_formula': '2 * (open_close_2fgm / open_close_2fga)',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'cont_long_2fga': {
        'stat_category': 'tracking',
        'display_name': 'CL2A',
        'description': 'Contested long two-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'cont_2fga - cont_close_2fga',
        'team_formula': 'cont_2fga - cont_close_2fga',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'points_per_cont_long_2fga': {
        'stat_category': 'tracking',
        'display_name': 'PCL2',
        'description': 'Points per contested long two attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2 * ((cont_2fgm - cont_close_2fgm) / (cont_2fga - cont_close_2fga))',
        'team_formula': '2 * ((cont_2fgm - cont_close_2fgm) / (cont_2fga - cont_close_2fga))',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'open_long_2fga': {
        'stat_category': 'tracking',
        'display_name': 'OL2A',
        'description': 'Open long two-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'open_2fga - open_close_2fga',
        'team_formula': 'open_2fga - open_close_2fga',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'points_per_open_long_2fga': {
        'stat_category': 'tracking',
        'display_name': 'POL2',
        'description': 'Points per open long two attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2* ((open_2fgm - open_close_2fgm) / (open_2fga - open_close_2fga))',
        'team_formula': '2* ((open_2fgm - open_close_2fgm) / (open_2fga - open_close_2fga))',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    '3fga': {
        'stat_category': 'basic',
        'display_name': '3A',
        'description': 'Three-point field goal attempts',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'basic',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '3fga',
        'team_formula': '3fga',
        'opponents_formula': 'opp_3fga',
        'minimum_width': 'auto',
    },
    
    'Points_Per_Three_attempt': {
        'stat_category': 'basic',
        'display_name': 'P3',
        'description': 'Points per three-point attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'basic',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '3 * (3fgm / 3fga)',
        'team_formula': '3 * (3fgm / 3fga)',
        'opponents_formula': '3 * (opp_3fgm / opp_3fga)',
        'minimum_width': 'auto',
    },
    
    'cont_3fga': {
        'stat_category': 'tracking',
        'display_name': 'C3A',
        'description': 'Contested three-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'cont_3fga',
        'team_formula': 'cont_3fga',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'points_per_cont_3fga': {
        'stat_category': 'tracking',
        'display_name': 'PC3',
        'description': 'Points per contested three attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '3 * (cont_3fgm / cont_3fga)',
        'team_formula': '3 * (cont_3fgm / cont_3fga)',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'open_3fga': {
        'stat_category': 'tracking',
        'display_name': 'O3A',
        'description': 'Open three-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'open_3fga',
        'team_formula': 'open_3fga',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'points_per_open_3fga': {
        'stat_category': 'tracking',
        'display_name': 'PO3',
        'description': 'Points per open three attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '3 * (open_3fgm / open_3fga)',
        'team_formula': '3 * (open_3fgm / open_3fga)',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'free_throw_rate': {
        'stat_category': 'basic',
        'display_name': 'FTR',
        'description': 'Free throw attempts per field goal attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'FTA',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'fta',
                'team_formula': 'fta',
                'opponents_formula': 'opp_fta',
            },
        },
        'player_formula': 'fta / (2fga + 3fga)',
        'team_formula': 'fta / (2fga + 3fga)',
        'opponents_formula': 'opp_fta / (opp_2fga + opp_3fga)',
        'minimum_width': 'auto',
    },
    
    'points_per_ft': {
        'stat_category': 'basic',
        'display_name': 'PFT',
        'description': 'Points per free throw',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': 'ftm / fta',
        'team_formula': 'ftm / fta',
        'opponents_formula': 'opp_ftm / opp_fta',
        'minimum_width': 'auto',
    },
    
    'assists': {
        'stat_category': 'basic',
        'display_name': 'AST',
        'description': 'Assists per 100 possessions',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'AST',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'assists',
                'team_formula': 'assists',
                'opponents_formula': 'opp_assists',
            },
        },
        'player_formula': '(assists / possessions) * 100',
        'team_formula': '(assists / possessions) * 100',
        'opponents_formula': '(opp_assists / possessions) * 100',
        'minimum_width': 30,
    },
    
    'potential_assists': {
        'stat_category': 'tracking',
        'display_name': 'PAST',
        'description': 'Potential assists (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'pot_assists',
        'team_formula': 'pot_assists',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'secondary_assists': {
        'stat_category': 'tracking',
        'display_name': '2AST',
        'description': 'Secondary assists (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'sec_assists',
        'team_formula': 'sec_assists',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'passes': {
        'stat_category': 'tracking',
        'display_name': 'Pass',
        'description': 'Total passes made (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'passes',
        'team_formula': 'passes',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'touches': {
        'stat_category': 'tracking',
        'display_name': 'Tou',
        'description': 'Total touches (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'touches',
        'team_formula': 'touches',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'seconds_per_touch': {
        'stat_category': 'tracking',
        'display_name': 'SPT',
        'description': 'Average seconds per touch (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'time_on_ball / touches',
        'team_formula': 'time_on_ball / touches',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'dribbles_per_touch': {
        'stat_category': 'tracking',
        'display_name': 'DPT',
        'description': 'Average dribbles per touch (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'dribbles / touches',
        'team_formula': 'dribbles / touches',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'turnover_pct': {
        'stat_category': 'basic',
        'display_name': 'TOV%',
        'description': 'Turnovers per possession (%)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'TOV',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'turnovers',
                'team_formula': 'turnovers',
                'opponents_formula': 'opp_turnovers',
            },
        },
        'player_formula': '(turnovers / possessions) * 100',
        'team_formula': '(turnovers / possessions) * 100',
        'opponents_formula': '(opp_turnovers / possessions) * 100',
        'minimum_width': 'auto',
    },
    
    'oreb_pct': {
        'stat_category': 'basic',
        'display_name': 'OR%',
        'description': 'Offensive rebound percentage',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'OREB',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'o_rebounds',
                'team_formula': 'o_rebounds',
                'opponents_formula': 'opp_o_rebounds',
            },
        },
        'player_formula': 'o_rebound_pct_x1000 / 10',
        'team_formula': 'o_rebound_pct_x1000 / 10',
        'opponents_formula': None,
        'minimum_width': 30,
    },
    
    'dreb_pct': {
        'stat_category': 'basic',
        'display_name': 'DR%',
        'description': 'Defensive rebound percentage',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'DRS',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'd_rebounds',
                'team_formula': 'd_rebounds',
                'opponents_formula': 'opp_d_rebounds',
            },
        },
        'player_formula': 'd_rebound_pct_x1000 / 10',
        'team_formula': 'd_rebound_pct_x1000 / 10',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'cont_oreb_pct': {
        'stat_category': 'tracking',
        'display_name': 'COR%',
        'description': 'Contested offensive rebound % (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'COR',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'cont_o_rebs',
                'team_formula': 'cont_o_rebs',
                'opponents_formula': None,
            },
        },
        'player_formula': '(cont_o_rebs / o_rebounds) * 100',
        'team_formula': '(cont_o_rebs / o_rebounds) * 100',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'cont_dreb_pct': {
        'stat_category': 'tracking',
        'display_name': 'CDR%',
        'description': 'Contested defensive rebound % (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'CDR',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'cont_d_rebs',
                'team_formula': 'cont_d_rebs',
                'opponents_formula': None,
            },
        },
        'player_formula': '(cont_d_rebs / d_rebounds) * 100',
        'team_formula': '(cont_d_rebs / d_rebounds) * 100',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'putback_pct': {
        'stat_category': 'tracking',
        'display_name': 'PB%',
        'description': 'Putbacks per offensive rebound % (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'player_formula': '(putbacks / o_rebounds) * 100',
        'team_formula': '(putbacks / o_rebounds) * 100',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'off_distance': {
        'stat_category': 'tracking',
        'display_name': 'Off Dist',
        'description': 'Offensive distance traveled in miles (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'movement',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'o_dist_x10 / 10',
        'team_formula': None,
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'def_distance': {
        'stat_category': 'tracking',
        'display_name': 'Def Dist',
        'description': 'Defensive distance traveled in miles (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'movement',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'd_dist_x10 / 10',
        'team_formula': None,
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'def_close_2fga': {
        'stat_category': 'tracking',
        'display_name': 'DC2A',
        'description': 'Defended close two-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'd_close_2fga',
        'team_formula': 'd_close_2fga',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'points_per_def_close_2fga': {
        'stat_category': 'tracking',
        'display_name': 'PDC2',
        'description': 'Points allowed per defended close two',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2 * (d_close_2fgm / d_close_2fga)',
        'team_formula': '2 * (d_close_2fgm / d_close_2fga)',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'def_long_2fga': {
        'stat_category': 'tracking',
        'display_name': 'DL2A',
        'description': 'Defended long two-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'd_2fga - d_close_2fga',
        'team_formula': None,
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'points_per_def_long_2fga': {
        'stat_category': 'tracking',
        'display_name': 'PDL2',
        'description': 'Points allowed per defended long two',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '2 * ((d_2fgm - d_close_2fgm) / (d_2fga - d_close_2fga))',
        'team_formula': '2 * ((d_2fgm - d_close_2fgm) / (d_2fga - d_close_2fga))',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'def_3fga': {
        'stat_category': 'tracking',
        'display_name': 'D3A',
        'description': 'Defended three-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'd_3fga',
        'team_formula': 'd_3fga',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'points_per_def_3fga': {
        'stat_category': 'tracking',
        'display_name': 'PD3',
        'description': 'Points allowed per defended three',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'player_formula': '3 * (d_3fgm / d_3fga)',
        'team_formula': '3 * (d_3fgm / d_3fga)',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'real_def_pct': {
        'stat_category': 'tracking',
        'display_name': 'RD%',
        'description': 'Real defensive FG% (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'player_formula': 'real_d_fg_pct_x1000 / 1000',
        'team_formula': 'real_d_fg_pct_x1000 / 1000',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'blocks': {
        'stat_category': 'basic',
        'display_name': 'Blk',
        'description': 'Blocks',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'blocks',
        'team_formula': 'blocks',
        'opponents_formula': 'opp_blocks',
        'minimum_width': 'auto',
    },
    
    'contests': {
        'stat_category': 'hustle',
        'display_name': 'Cont',
        'description': 'Shot contests (hustle)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'contests',
        'team_formula': 'contests',
        'opponents_formula': 'opp_contests',
        'minimum_width': 'auto',
    },
    
    'steals_plus_charges': {
        'stat_category': 'basic',
        'display_name': 'TOVF',
        'description': 'Steals plus charges per 100 possessions',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'mode_overrides': {
            'totals': {
                'display_name': 'TOVF',
                'format': 'number',
                'decimal_places': 1,
                'player_formula': 'steals + charges_drawn',
                'team_formula': 'steals + charges',
                'opponents_formula': None,
            },
        },
        'player_formula': '((steals + charges_drawn) / possessions) * 100',
        'team_formula': '((steals + charges_drawn) / possessions) * 100',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'deflections': {
        'stat_category': 'hustle',
        'display_name': 'DFLS',
        'description': 'Deflections (hustle)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'advanced',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'deflections',
        'team_formula': 'deflections',
        'opponents_formula': 'opp_deflections',
        'minimum_width': 'auto',
    },
    
    'fouls': {
        'stat_category': 'basic',
        'display_name': 'Fls',
        'description': 'Personal fouls',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'fouls',
        'team_formula': 'fouls',
        'opponents_formula': 'opp_fouls',
        'minimum_width': 'auto',
    },
    
    'o_rating': {
        'stat_category': 'basic',
        'display_name': 'ORT',
        'description': 'Offensive rating per 100 possessions',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'onoff',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'o_rating_x10 / 10',
        'team_formula': 'o_rating_x10 / 10',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'd_rating': {
        'stat_category': 'basic',
        'display_name': 'DRT',
        'description': 'Defensive rating per 100 possessions',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'onoff',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': 'd_rating_x10 / 10',
        'team_formula': 'd_rating_x10 / 10',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'net_off_o_rating': {
        'stat_category': 'basic',
        'display_name': 'NOOO',
        'description': 'Net Offensive on/off Team Rating',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'onoff',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '(o_rating_x10 / 10) - (off_o_rating_x10 / 10)',
        'team_formula': None,
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    'net_off_d_rating': {
        'stat_category': 'basic',
        'display_name': 'NDOO',
        'description': 'Net Defensive on/off Team Rating',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'onoff',
        'stat_mode': 'both',
        'has_percentile': True,
        'is_stat': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'player_formula': '(d_rating_x10 / 10) - (off_d_rating_x10 / 10)',
        'team_formula': None,
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
    
    # ========================================================================
    # IDENTITY SECTION
    # ========================================================================
    
    'nba_id': {
        'stat_category': 'none',
        'display_name': 'NBA ID',
        'description': 'NBA.com player/team ID',
        'section': ['identity'],
        'subsection': None,
        'stat_mode': 'both',
        'has_percentile': False,
        'is_stat': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'player_formula': 'player_id',
        'team_formula': 'team_id',
        'opponents_formula': None,
        'minimum_width': 'auto',
    },
}
