"""
The Glass - Publish Column Registry

Tab column definitions (TAB_COLUMNS) and the field-derivation logic that
maps display columns back to database column references.
"""

from typing import Any, Dict

from src.publish.core.formulas import (
    add, subtract, multiply, divide, lookup, team_average, seasons_in_query, calculate_age
)

# ============================================================================
# COLUMN DEFINITIONS
# ============================================================================

# Valid attribute value sets (co-located with the schema they constrain)
_VALID_SECTIONS = {
    'entities', 'profile', 'evaluation',
    'current_stats', 'historical_stats', 'postseason_stats', 'identity',
}
_VALID_SUBSECTIONS = {
    'rates', 'scoring', 'ball_management', 'rebounding',
    'distance', 'defense', 'opponent', 'team_ratings', 'nba',
    'League', 'Player',
}
_VALID_TABS = {'all_teams', 'all_players', 'individual_team'}
_VALID_STATS_MODES = {'basic', 'advanced', 'both'}
_VALID_FORMATS = {'text', 'number', 'percentage', 'measurement'}
_VALID_WIDTH_CLASSES = {
    'auto', 'measurement', 'four_char', 'four_char_dec',
    'three_char_dec', 'two_char', 'two_char_dec'
}
_VALID_WIDTH_CLASS_TYPES = (str, int)
_VALID_LEAGUES = {'nba', 'ncaa'}

_VALID_ALIGNS = {'left', 'center'}
_VALID_EMPHASIS = {'bold', None}

TAB_COLUMNS_SCHEMA = {
    'description':     {'required': True,  'types': (str,)},
    'sections':        {'required': True,  'types': (list,),        'list_item_values': _VALID_SECTIONS},
    'subsection':      {'required': True,  'types': (str, type(None)), 'allowed_values': _VALID_SUBSECTIONS | {None}},
    'tabs':            {'required': True,  'types': (list,),        'list_item_values': _VALID_TABS},
    'stats_mode':      {'required': True,  'types': (str,),         'allowed_values': _VALID_STATS_MODES},
    'percentile':      {'required': True,  'types': (str, type(None)), 'allowed_values': {'standard', 'reverse', None}},
    'editable':        {'required': True,  'types': (bool,)},
    'scale_with_rate': {'required': True,  'types': (bool,)},
    'format':          {'required': True,  'types': (str,),         'allowed_values': _VALID_FORMATS},
    'decimal_places':  {'required': True,  'types': (int, type(None))},
    'width_class':     {'required': True,  'types': _VALID_WIDTH_CLASS_TYPES},
    'leagues':         {'required': True,  'types': (list,),        'list_item_values': _VALID_LEAGUES},
    'default':         {'required': True,  'types': (str, int, float, type(None))},
    'align':           {'required': False, 'types': (str,),         'allowed_values': _VALID_ALIGNS, 'default': 'center'},
    'emphasis':        {'required': False, 'types': (str, type(None)), 'allowed_values': _VALID_EMPHASIS, 'default': None},
    'font_size':       {'required': False, 'types': (int, type(None)), 'default': None},
    'values':          {'required': True,  'types': (dict,)},
}

TAB_COLUMNS: Dict[str, Any] = {
    'name': {
        'description': 'Name',
        'sections': ['entities'],
        'subsection': None,
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': False,
        'scale_with_rate': False,
        'format': 'text',
        'decimal_places': None,
        'width_class': 'auto',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'left',
        'emphasis': 'bold',
        'font_size': 10,
        'values': {
            'player': '{name}',
            'team': 'TEAM',
            'all_teams': '{name}',
            'opponents': 'OPPONENTS'
        }
    },
    'team': {
        'description': 'Team Abbreviation',
        'sections': ['profile'],
        'subsection': 'League',
        'tabs': ['all_players'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': False,
        'scale_with_rate': False,
        'format': 'text',
        'decimal_places': None,
        'width_class': 'four_char',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': lookup('team_id', 'all_teams', 'abbr')
        }
    },
    'conf': {
        'description': 'Conference',
        'sections': ['profile'],
        'subsection': 'League',
        'tabs': ['all_teams'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': False,
        'scale_with_rate': False,
        'format': 'text',
        'decimal_places': None,
        'width_class': 'four_char',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'all_teams': '{conf}'
        }
    },
    'J#': {
        'description': 'Jersey Number',
        'sections': ['profile'],
        'subsection': 'League',
        'tabs': ['all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': False,
        'scale_with_rate': False,
        'format': 'text',
        'decimal_places': None,
        'width_class': 'two_char',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{jersey_num}'
        }
    },
    'exp': {
        'description': 'Seasons with Playing Experience',
        'sections': ['profile'],
        'subsection': 'League',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'two_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_display': 'average',
        'default': '0',
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{seasons_exp}',
            'team': team_average('seasons_exp'),
            'all_teams': team_average('seasons_exp')
        }
    },
    'age': {
        'description': 'Age',
        'sections': ['profile'],
        'subsection': 'Player',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'reverse',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': calculate_age('birthdate'),
            'team': team_average(calculate_age('birthdate')),
            'all_teams': team_average(calculate_age('birthdate'))
        },
    },
    'ht': {
        'description': 'Height in Feet\'Inches"',
        'sections': ['profile'],
        'subsection': 'Player',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'measurement',
        'decimal_places': 1,
        'width_class': 'measurement',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{height_ins}',
            'team': team_average('height_ins'),
            'all_teams': team_average('height_ins')
        }
    },
    'wt': {
        'description': 'Weight in Pounds',
        'sections': ['profile'],
        'subsection': 'Player',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{weight_lbs}',
            'team': team_average('weight_lbs'),
            'all_teams': team_average('weight_lbs')
        }
    },
    'ws': {
        'description': 'Wingspan in Feet\'Inches" (Editable)',
        'sections': ['profile'],
        'subsection': 'Player',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': True,
        'scale_with_rate': False,
        'format': 'measurement',
        'decimal_places': 1,
        'width_class': 'measurement',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{wingspan_ins}',
            'team': team_average('wingspan_ins'),
            'all_teams': team_average('wingspan_ins')
        }
    },
    '🖐️': {
        'description': 'Handedness (Editable)',
        'sections': ['profile'],
        'subsection': 'Player',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': True,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 0,
        'width_class': 'two_char',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{hand}'
        }
    },
    'notes': {
        'description': 'Personal thoughts, observations, findings, etc (Editable)',
        'sections': ['evaluation'],
        'subsection': None,
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': True,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 0,
        'width_class': 500,
        'leagues': ['nba', 'ncaa'],
        'team_row_display': 'editable',
        'default': None,
        'align': 'left',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{notes}',
            'team': '{notes}',
            'all_teams': '{notes}'
        }
    },
    'szn': {
        'description': 'Seasons Played',
        'sections': ['historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 0,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': 0,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': seasons_in_query,
            'team': seasons_in_query,
            'all_teams': seasons_in_query
        }
    },
    'gms': {
        'description': 'Games Played per Season',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': 0,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': divide('games', seasons_in_query),
            'team': divide('games', seasons_in_query),
            'all_teams': divide('games', seasons_in_query)
        },
    },
    'min': {
        'description': 'Minutes Played per Game',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_display': 'team_value',
        'default': 0,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': divide(divide('minutes_x10', 10), 'games'),
            'team': divide(divide('minutes_x10', 10), 'games'),
            'all_teams': divide(divide('minutes_x10', 10), 'games')
        }
    },
    'pace': {
        'description': 'Possessions per 40 Mins',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': divide(multiply('possessions', 40), divide('minutes_x10', 10)),
            'team': divide(multiply('possessions', 40), divide('minutes_x10', 10)),
            'all_teams': divide(multiply('possessions', 40), divide('minutes_x10', 10))
        }
    },
    'pts': {
        'description': 'Points',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': add(multiply('fg2m', 2), multiply('fg3m', 3), 'ftm'),
            'team': add(multiply('fg2m', 2), multiply('fg3m', 3), 'ftm'),
            'all_teams': add(multiply('fg2m', 2), multiply('fg3m', 3), 'ftm'),
            'opponents': add(multiply('opp_fg2m', 2), multiply('opp_fg3m', 3), 'opp_ftm')
        }
    },
    'p/ta': {
        'description': 'Points per "True" FGA (FGA + FTA per FT Trip Estimation) or TS% * 2',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': divide(add(multiply('fg2m', 2), multiply('fg3m', 3), 'ftm'), add('fg2a', 'fg3a', multiply(0.44, 'fta'))),
            'team': divide(add(multiply('fg2m', 2), multiply('fg3m', 3), 'ftm'), add('fg2a', 'fg3a', multiply(0.44, 'fta'))),
            'all_teams': divide(add(multiply('fg2m', 2), multiply('fg3m', 3), 'ftm'), add('fg2a', 'fg3a', multiply(0.44, 'fta'))),
            'opponents': divide(add(multiply('opp_fg2m', 2), multiply('opp_fg3m', 3), 'opp_ftm'), add('opp_fg2a', 'opp_fg3a', multiply(0.44, 'opp_fta')))
        }
    },
    '2a': {
        'description': 'Two-Point FGA',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{fg2a}',
            'team': '{fg2a}',
            'all_teams': '{fg2a}',
            'opponents': '{opp_fg2a}'
        }
    },
    'p/2': {
        'description': 'Points per 2A',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': multiply(2, divide('fg2m', 'fg2a')),
            'team': multiply(2, divide('fg2m', 'fg2a')),
            'all_teams': multiply(2, divide('fg2m', 'fg2a')),
            'opponents': multiply(2, divide('opp_fg2m', 'opp_fg2a'))
        }
    },
    'ora': {
        'description': 'Open 2A at the Rim (Closest Defender Beyond 4 Feet; Shot Taken Within 5 feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{open_rim_fga}',
            'team': '{open_rim_fga}',
            'all_teams': '{open_rim_fga}'
        }
    },
    'p/or': {
        'description': 'Points per Open 2A at the Rim (Closest Defender Beyond 4 Feet; Shot Taken Within 5 feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': multiply(2, divide('open_rim_fgm', 'open_rim_fga')),
            'team': multiply(2, divide('open_rim_fgm', 'open_rim_fga')),
            'all_teams': multiply(2, divide('open_rim_fgm', 'open_rim_fga'))
        }
    },
    'cra': {
        'description': 'Contested 2A at the Rim (Closest Defender Within 4 Feet; Shot Taken Within 5 feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{cont_rim_fga}',
            'team': '{cont_rim_fga}',
            'all_teams': '{cont_rim_fga}'
        }
    },
    'p/cr': {
        'description': 'Points per Contested 2A at the Rim (Closest Defender Within 4 Feet; Shot Taken Within 5 feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': multiply(2, divide('cont_rim_fgm', 'cont_rim_fga')),
            'team': multiply(2, divide('cont_rim_fgm', 'cont_rim_fga')),
            'all_teams': multiply(2, divide('cont_rim_fgm', 'cont_rim_fga'))
        }
    },
    'uar': {
        'description': 'Unassisted 2A Made at the Rim (Shot Taken Within 5 feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{unassisted_rim_fgm}',
            'team': '{unassisted_rim_fgm}',
            'all_teams': '{unassisted_rim_fgm}'
        }
    },
    'oma': {
        'description': 'Open 2A in the Mid-Range (Closest Defender Beyond 4 Feet; Shot Taken Beyond 5 feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': subtract('cont_fg2a', 'cont_rim_fga'),
            'team': subtract('cont_fg2a', 'cont_rim_fga'),
            'all_teams': subtract('cont_fg2a', 'cont_rim_fga')
        }
    },
    'p/om': {
        'description': 'Points per Open 2A in the Mid-Range (Closest Defender Beyond 4 Feet; Shot Taken Beyond 5 feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': multiply(2, divide(subtract('open_fg2m', 'open_rim_fgm'), subtract('open_fg2a', 'open_rim_fga'))),
            'team': multiply(2, divide(subtract('open_fg2m', 'open_rim_fgm'), subtract('open_fg2a', 'open_rim_fga'))),
            'all_teams': multiply(2, divide(subtract('open_fg2m', 'open_rim_fgm'), subtract('open_fg2a', 'open_rim_fga')))
        }
    },
    'cma': {
        'description': 'Contested 2A in the Mid-Range (Closest Defender Within 4 Feet; Shot Taken Beyond 5 feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': subtract('cont_fg2a', 'cont_rim_fga'),
            'team': subtract('cont_fg2a', 'cont_rim_fga'),
            'all_teams': subtract('cont_fg2a', 'cont_rim_fga')
        }
    },
    'p/cm': {
        'description': 'Points per Contested 2A in the Mid-Range (Closest Defender Within 4 Feet; Shot Taken Within 5 feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': multiply(2, divide(subtract('cont_fg2m', 'cont_rim_fgm'), subtract('cont_fg2a', 'cont_rim_fga'))),
            'team': multiply(2, divide(subtract('cont_fg2m', 'cont_rim_fgm'), subtract('cont_fg2a', 'cont_rim_fga'))),
            'all_teams': multiply(2, divide(subtract('cont_fg2m', 'cont_rim_fgm'), subtract('cont_fg2a', 'cont_rim_fga')))
        }
    },
    'uam': {
        'description': 'Unassisted 2A Made in the Mid-Range (Shot Taken Beyond 5 feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': subtract('unassisted_fg2m', 'unassisted_rim_fgm'),
            'team': subtract('unassisted_fg2m', 'unassisted_rim_fgm'),
            'all_teams': subtract('unassisted_fgm', 'unassisted_rim_fgm')
        }
    },
    '3a': {
        'description': 'Three-Point FGA',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{fg3a}',
            'team': '{fg3a}',
            'all_teams': '{fg3a}',
            'opponents': '{opp_fg3a}'
        }
    },
    'p/3': {
        'description': 'Points per 3A',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': multiply(3, divide('fg3m', 'fg3a')),
            'team': multiply(3, divide('fg3m', 'fg3a')),
            'all_teams': multiply(3, divide('fg3m', 'fg3a')),
            'opponents': multiply(3, divide('opp_fg3m', 'opp_fg3a'))
        }
    },
    'o3a': {
        'description': 'Open 3A (Closest Defender Beyond 4 Feet)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{open_fg3a}',
            'team': '{open_fg3a}',
            'all_teams': '{open_fg3a}'
        }
    },
    'p/o3': {
        'description': 'Points per Open 3A (Closest Defender Beyond 4 Feet)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': multiply(3, divide('open_fg3m', 'open_fg3a')),
            'team': multiply(3, divide('open_fg3m', 'open_fg3a')),
            'all_teams': multiply(3, divide('open_fg3m', 'open_fg3a'))
        }
    },
    'c3a': {
        'description': 'Contested 3A (Closest Defender Within 4 Feet)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{cont_fg3a}',
            'team': '{cont_fg3a}',
            'all_teams': '{cont_fg3a}'
        }
    },
    'p/c3': {
        'description': 'Points per Contested 3A (Closest Defender Within 4 Feet)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': multiply(3, divide('cont_fg3m', 'cont_fg3a')),
            'team': multiply(3, divide('cont_fg3m', 'cont_fg3a')),
            'all_teams': multiply(3, divide('cont_fg3m', 'cont_fg3a'))
        }
    },
    'ua3': {
        'description': 'Unassisted 3A Made',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{unassisted_fg3m}',
            'team': '{unassisted_fg3m}',
            'all_teams': '{unassisted_fg3m}'
        }
    },
    'ftr': {
        'description': 'Free throw Rate (FTA / FGA)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': divide('fta', add('fg2a', 'fg3a')),
            'team': divide('fta', add('fg2a', 'fg3a')),
            'all_teams': divide('fta', add('fg2a', 'fg3a')),
            'opponents': divide('opp_fta', add('opp_fg2a', 'opp_fg3a'))
        }
    },
    'p/ft': {
        'description': 'Points per FTA',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_display': 'team_value',
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': divide('ftm', 'fta'),
            'team': divide('ftm', 'fta'),
            'all_teams': divide('ftm', 'fta'),
            'opponents': divide('opp_ftm', 'opp_fta')
        }
    },
    'dnk': {
        'description': 'Dunks',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{dunks}',
            'team': '{dunks}',
            'all_teams': '{dunks}'
        }
    },
    'tou': {
        'description': 'Instances of Holding the Ball',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{touches}',
            'team': '{touches}',
            'all_teams': '{touches}'
        }
    },
    'spt': {
        'description': 'Seconds per Touch',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'reverse',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'two_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': divide(multiply(60, 'time_on_ball'), 'touches'),
            'team': divide(multiply(60, 'time_on_ball'), 'touches'),
            'all_teams': divide(multiply(60, 'time_on_ball'), 'touches')
        }
    },
    '%trs': {
        'description': 'Percentage of Touches Resulting in a Shot',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': multiply(100, divide(add('fg2a', 'fg3a', multiply(0.44, 'fta')), 'touches')),
            'team': multiply(100, divide(add('fg2a', 'fg3a', multiply(0.44, 'fta')), 'touches')),
            'all_teams': multiply(100, divide(add('fg2a', 'fg3a', multiply(0.44, 'fta')), 'touches'))
        }
    },
    '%trp': {
        'description': 'Percentage of Touches Resulting in a Pass',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': multiply(100, divide('passes', 'touches')),
            'team': multiply(100, divide('passes', 'touches')),
            'all_teams': multiply(100, divide('passes', 'touches'))
        }
    },
    '%trt': {
        'description': 'Percentage of Touches Resulting in a Turnover',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'reverse',
        'editable': False,
        'scale_with_rate': False,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': multiply(100, divide('turnovers', 'touches')),
            'team': multiply(100, divide('turnovers', 'touches')),
            'all_teams': multiply(100, divide('turnovers', 'touches'))
        }
    },
    'ast': {
        'description': 'Assists',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{assists}',
            'team': '{assists}',
            'all_teams': '{assists}',
            'opponents': '{opp_assists}'
        }
    },
    'past': {
        'description': 'Potential Assists (Passes that lead to a FGA)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{pot_assists}',
            'team': '{pot_assists}',
            'all_teams': '{pot_assists}'
        }
    },
    '2ast': {
        'description': 'Secondary Assists (Passes that Lead to an Assist)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_display': 'team_value',
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{sec_assists}',
            'team': '{sec_assists}',
            'all_teams': '{sec_assists}'
        }
    },
    'tov': {
        'description': 'Turnovers',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'reverse',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{turnovers}',
            'team': '{turnovers}',
            'opponents': '{opp_turnovers}'
        }
    },
    'or%': {
        'description': 'Offensive Rebound Percentage',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': divide('o_reb_pct_x1000', 10),
            'team': divide('o_reb_pct_x1000', 10),
            'all_teams': divide('o_reb_pct_x1000', 10)
        }
    },
    'cor%': {
        'description': 'Contested Offensive Rebound Percentage (Percentage of Offensive Rebounds that are Contested)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_display': 'team_value',
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': divide('cont_o_rebs', 'o_rebs'),
            'team': divide('cont_o_rebs', 'o_rebs'),
            'all_teams': divide('cont_o_rebs', 'o_rebs')
        }
    },
    'dr%': {
        'description': 'Defensive Rebound Percentage',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': divide('d_reb_pct_x1000', 10),
            'team': divide('d_reb_pct_x1000', 10),
            'all_teams': divide('d_reb_pct_x1000', 10)
        }
    },
    'cdr%': {
        'description': 'Contested Defensive Rebound Percentage (Percentage of Defensive Rebounds that are Contested)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': divide('cont_d_rebs', 'd_rebs'),
            'team': divide('cont_d_rebs', 'd_rebs'),
            'all_teams': divide('cont_d_rebs', 'd_rebs')
        }
    },
    'pb%': {
        'description': 'Putbacks Percentage (Percentage of Offensive Rebounds that are Putbacks)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': divide('putbacks', 'o_rebs'),
            'team': divide('putbacks', 'o_rebs'),
            'all_teams': divide('putbacks', 'o_rebs')
        }
    },
    'odst': {
        'description': 'Offensive Distance Traveled in Miles',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'distance',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': divide('o_dist_x10', 10),
            'team': divide('o_dist_x10', 10),
            'all_teams': divide('o_dist_x10', 10)
        }
    },
    'ddst': {
        'description': 'Defensive Distance Traveled in Miles',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'distance',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': divide('d_dist_x10', 10),
            'team': divide('d_dist_x10', 10),
            'all_teams': divide('d_dist_x10', 10)
        }
    },
    'dra': {
        'description': 'Defended 2A at the Rim (Closest Defender for FGA Within 5 Feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{d_rim_fga}',
            'team': '{d_rim_fga}',
            'all_teams': '{d_rim_fga}'
        }
    },
    'p/dr': {
        'description': 'Points Allowed per Defended FGA at the Rim (Closest Defender for FGA Within 5 Feet of the Rim)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'reverse',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': multiply(2, divide('d_rim_fgm', 'd_rim_fga')),
            'team': multiply(2, divide('d_rim_fgm', 'd_rim_fga')),
            'all_teams': multiply(2, divide('d_rim_fgm', 'd_rim_fga'))
        }
    },
    'dma': {
        'description': 'Defended 2A in the Mid-Range (Closest Defender for FGA Beyond 5 Feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': subtract('d_fg2a', 'd_rim_fga'),
            'team': subtract('d_fg2a', 'd_rim_fga'),
            'all_teams': subtract('d_fg2a', 'd_rim_fga')
        }
    },
    'p/dm': {
        'description': 'Points Allowed per Defended FGA in the Mid-Range (Closest Defender for FGA Beyond 5 Feet of the Rim and Within the Three-Point Line)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'reverse',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': multiply(2, divide(subtract('d_fg2m', 'd_rim_fgm'), subtract('d_fg2a', 'd_rim_fga'))),
            'team': multiply(2, divide(subtract('d_fg2m', 'd_rim_fgm'), subtract('d_fg2a', 'd_rim_fga'))),
            'all_teams': multiply(2, divide(subtract('d_fg2m', 'd_rim_fgm'), subtract('d_fg2a', 'd_rim_fga')))
        }
    },
    'd3a': {
        'description': 'Defended 3A (Closest Defender)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{d_fg3a}',
            'team': '{d_fg3a}',
            'all_teams': '{d_fg3a}'
        }
    },
    'p/d3': {
        'description': 'Points Allowed per Defended 3A (Closest Defender)',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'advanced',
        'percentile': 'reverse',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': multiply(3, divide('d_fg3m', 'd_fg3a')),
            'team': multiply(3, divide('d_fg3m', 'd_fg3a')),
            'all_teams': multiply(3, divide('d_fg3m', 'd_fg3a'))
        }
    },
    'cont': {
        'description': 'Defensive Shot Contests',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{contests}',
            'team': '{contests}',
            'all_teams': '{contests}'
        }
    },
    'blk': {
        'description': 'Blocks',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{blocks}',
            'team': '{blocks}',
            'all_teams': '{blocks}',
            'opponents': '{opp_blocks}'
        }
    },
    'defl': {
        'description': 'Deflections of the ball on Defense',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{deflections}',
            'team': '{deflections}',
            'all_teams': '{deflections}'
        }
    },
    'stl': {
        'description': 'Steals',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{steals}',
            'team': '{steals}',
            'all_teams': '{steals}',
            'opponents': '{opp_steals}'
        }
    },
    'st+c': {
        'description': 'Steals + Charges Drawn',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': add('steals', 'charges_drawn'),
            'team': add('steals', 'charges_drawn'),
            'all_teams': add('steals', 'charges_drawn')
        }
    },
    'fls': {
        'description': 'Personal Fouls',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'basic',
        'percentile': 'reverse',
        'editable': False,
        'scale_with_rate': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': '{fouls}',
            'team': '{fouls}',
            'all_teams': '{fouls}',
            'opponents': '{opp_fouls}'
        }
    },
    'w%': {
        'description': 'Win percentage',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'team_ratings',
        'tabs': ['all_teams', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': multiply(divide('wins', 'games'), 100),
            'team': multiply(divide('wins', 'games'), 100),
            'all_teams': multiply(divide('wins', 'games'), 100)
        }
    },
    'ortg': {
        'description': 'Team Offensive Rating When On Court',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'team_ratings',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_display': 'team_value',
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': divide('o_rtg_x10', 10),
            'team': divide('o_rtg_x10', 10),
            'all_teams': divide('o_rtg_x10', 10)
        }
    },
    'drtg': {
        'description': 'Team Defensive Rating When On Court',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'team_ratings',
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'reverse',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'leagues': ['nba', 'ncaa'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': divide('d_rtg_x10', 10),
            'team': divide('d_rtg_x10', 10),
            'all_teams': divide('d_rtg_x10', 10)
        }
    },
    'nooo': {
        'description': 'Net Offensive On/Off Team Rating',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'team_ratings',
        'tabs': ['all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'standard',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': subtract(divide('o_rtg_x10', 10), divide('off_o_rtg_x10', 10))
        }
    },
    'ndoo': {
        'description': 'Net Defensive on/off Team Rating',
        'sections': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'team_ratings',
        'tabs': ['all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': 'reverse',
        'editable': False,
        'scale_with_rate': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'four_char_dec',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': subtract(divide('d_rtg_x10', 10), divide('off_d_rtg_x10', 10))
        }
    },
    'ID': {
        'description': 'The Glass Entity ID',
        'sections': ['identity'],
        'subsection': None,
        'tabs': ['all_teams', 'all_players', 'individual_team'],
        'stats_mode': 'both',
        'percentile': None,
        'editable': False,
        'scale_with_rate': False,
        'format': 'text',
        'decimal_places': 0,
        'width_class': 'auto',
        'leagues': ['nba'],
        'default': None,
        'align': 'center',
        'emphasis': None,
        'font_size': 9,
        'values': {
            'player': 'id',
            'team': 'id',
            'all_teams': 'id'
        }
    }
}