"""
Config Export — generate apps-script/config/generated.js for clasp push.

Usage:
    python -m src.sheets.config_export --league nba

This pre-computes all column metadata, section boundaries, editable-field
mappings, and stat-mode column ranges so that Code.js has zero runtime
dependency on the Python API.  Run once before `clasp push`.
"""

import argparse
import json
import logging
import os
from pathlib import Path

from dotenv import load_dotenv

from src.sheets.core.api import get_config_for_export

load_dotenv()

logger = logging.getLogger(__name__)

OUTPUT_DIR = Path(__file__).resolve().parents[2] / 'apps-script' / 'config'


def _build_mode_column_ranges(config: dict) -> dict:
    """Derive per-mode column index sets from column_metadata.

    Returns {sheet_key: {mode_name: [col_indices]}} where col_indices are
    1-indexed column numbers belonging to that stat mode variant.
    Non-mode columns (without '__' in sec) are omitted — they are always visible.
    """
    result = {}
    for sheet_key, meta_list in (config.get('column_metadata') or {}).items():
        by_mode = {}
        for meta in meta_list:
            sec = meta.get('sec', '')
            if '__' not in sec:
                continue
            _, mode = sec.split('__', 1)
            by_mode.setdefault(mode, []).append(meta['col'])
        result[sheet_key] = by_mode
    return result


def _build_editable_lookup(config: dict) -> dict:
    """Build a lookup for linked-cell propagation.

    Returns {col_key: {db_field, display_name, format, team_row_calc,
                       indices: {sheet_key: col_index}}}
    """
    lookup = {}
    for ec in config.get('editable_columns') or []:
        key = ec['col_key']
        entry = {
            'db_field': ec['db_field'],
            'display_name': ec['display_name'],
            'format': ec.get('format', 'text'),
            'team_row_calc': ec.get('team_row_calc'),
            'indices': {},
        }
        for k, v in ec.items():
            if k.endswith('_col_index') and v is not None:
                sheet_key = k.replace('_col_index', '_sheet')
                entry['indices'][sheet_key] = v
            elif k == 'team_col_index' and v is not None:
                entry['indices']['team_sheet'] = v
        lookup[key] = entry
    return lookup


def export_config(league: str) -> Path:
    """Generate config JS file and return its path."""
    config = get_config_for_export(league)

    config['mode_column_ranges'] = _build_mode_column_ranges(config)
    config['editable_lookup'] = _build_editable_lookup(config)

    # Remove API-specific fields that are no longer needed
    config.pop('api_base_url', None)
    if 'league' in config:
        config['league'].pop('api_prefix', None)
        config['league'].pop('sync_endpoint', None)

    config_json = json.dumps(config, indent=2, ensure_ascii=False)

    output_file = OUTPUT_DIR / f'{league.upper()}_generated.js'
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    js_content = (
        f'// Auto-generated by src/sheets/config_export.py — do not edit.\n'
        f'// Re-generate: python -m src.sheets.config_export --league {league}\n'
        f'var CONFIG = {config_json};\n'
    )

    output_file.write_text(js_content, encoding='utf-8')
    logger.info('Wrote %s (%d bytes)', output_file, len(js_content))
    return output_file


def main():
    logging.basicConfig(level=logging.INFO, format='%(message)s')
    parser = argparse.ArgumentParser(description='Export sheets config as JS for clasp push')
    parser.add_argument('--league', choices=['nba', 'ncaa'], required=True)
    args = parser.parse_args()

    path = export_config(args.league)
    print(f'Config exported to {path}')


if __name__ == '__main__':
    main()
