"""
THE GLASS - Display Configuration
Single source of truth for all display logic, calculations, formatting, and percentiles.

This config drives:
- Sheet column generation (sheets_sync.py)
- Stat calculations (stat_engine.py)
- Percentile generation (auto-generated columns)
- Section organization (player_info, analysis, rates, scoring, distribution, rebounding, defense, onoff, identity)
"""

import os

# ============================================================================
# GOOGLE SHEETS CONFIGURATION
# ============================================================================

GOOGLE_SHEETS_CONFIG = {
    'credentials_file': os.getenv('GOOGLE_CREDENTIALS_FILE'),
    'spreadsheet_id': os.getenv('GOOGLE_SPREADSHEET_ID'),
    'spreadsheet_name': os.getenv('GOOGLE_SPREADSHEET_NAME'),
    'scopes': [
        'https://www.googleapis.com/auth/spreadsheets',
        'https://www.googleapis.com/auth/drive'
    ],
}

# ============================================================================
# API CONFIGURATION
# ============================================================================

API_CONFIG = {
    'host': os.getenv('API_HOST'),
    'port': int(os.getenv('API_PORT')),
    'debug': os.getenv('API_DEBUG', 'False').lower() == 'true',
    'cors_enabled': True,
}

SERVER_CONFIG = {
    'production_host': os.getenv('PRODUCTION_HOST'),
    'production_port': int(os.getenv('PRODUCTION_PORT')),
    'ssh_user': os.getenv('SSH_USER'),
    'remote_dir': os.getenv('REMOTE_DIR'),
    'systemd_service': os.getenv('SYSTEMD_SERVICE'),
}

# ============================================================================
# STAT CALCULATION CONSTANTS
# ============================================================================

STAT_CONSTANTS = {
    'game_length_minutes': 48.0,        # NBA game length
    'ts_fta_multiplier': 0.44,          # True shooting FTA coefficient
    'default_per_minutes': 36.0,        # Default minutes for per-minute stats
    'default_per_possessions': 100.0,   # Default possessions for per-possession stats
}

# ============================================================================
# SECTION AND SUBSECTION DEFINITIONS
# ============================================================================

# Top-level sections (periods) - correspond to Row 1 merged headers
SECTIONS = [
    'player_info',    # Team, Jersey, Experience, Age, Height, Weight, Wingspan
    'analysis',       # Notes (editable)
    'season',         # Current season stats (VALUES + PERCENTILES)
    'historical',     # Historical stats (VALUES + PERCENTILES)
    'postseason',     # Postseason/Playoff stats (VALUES + PERCENTILES)
    'identity',       # player_id (always hidden)
]

# Stat subsections - correspond to Row 2 subsection headers (within season/historical/postseason)
SUBSECTIONS = [
    'rates',          # Games, Minutes, Possessions
    'scoring',        # Points, TS%, FG2/3, Rim/Mid/3PT tracking, FT
    'distribution',   # Touches, Assists, Potential Assists, Turnovers
    'rebounding',     # OREB%, DREB%, Contested OREB/DREB%, Putbacks
    'defense',        # Defended shots, Steals, Deflections, Blocks, Contests, Charges, Fouls
    'onoff',          # Offensive/Defensive Rating, Off-court ratings
]

# ============================================================================
# COLORS & PERCENTILES
# ============================================================================

COLORS = {
    'red': {'red': 0.933, 'green': 0.294, 'blue': 0.169},
    'yellow': {'red': 0.988, 'green': 0.961, 'blue': 0.373},
    'green': {'red': 0.298, 'green': 0.733, 'blue': 0.090},
    'black': {'red': 0, 'green': 0, 'blue': 0},
    'white': {'red': 1, 'green': 1, 'blue': 1},
    'light_gray': {'red': 0.95, 'green': 0.95, 'blue': 0.95},
    'dark_gray': {'red': 67/255, 'green': 67/255, 'blue': 67/255},
}

COLOR_THRESHOLDS = {
    'low': 0,    # 0% = pure red
    'mid': 50,   # 50% = pure yellow
    'high': 100, # 100% = pure green
}

# ============================================================================
# SHEET FORMAT
# ============================================================================

SHEET_FORMAT = {
    'fonts': {
        'header_primary': {'family': 'Staatliches', 'size': 12},
        'header_secondary': {'family': 'Staatliches', 'size': 10},
        'team_name': {'family': 'Staatliches', 'size': 15},
        'player_names': {'family': 'Sofia Sans', 'size': 10},
        'data': {'family': 'Sofia Sans', 'size': 10},
    },
    'frozen': {
        'rows': 4,
        'columns': 1,  # Freeze only column A (team name)
    },
    'header_rows': 4,
}

# ============================================================================
# DISPLAY_COLUMNS - Master dictionary for all display columns
# ============================================================================

DISPLAY_COLUMNS = {
    # ========================================================================
    # PLAYER INFO SECTION
    # ========================================================================
    'team': {
        'key': 'team',
        'display_name': 'TM',
        'display_name_totals': 'TM',
        'section': 'player_info',
        'subsection': None,
        'view_mode': 'both',
        'calculation_type': 'db_direct',
        'source': 'team_abbr',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': 40,
        'decimals': 0,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': False,
        'totals_mode_override': None,
    },
    'jersey': {
        'key': 'jersey',
        'display_name': 'J#',
        'display_name_totals': 'J#',
        'section': 'player_info',
        'subsection': None,
        'view_mode': 'both',
        'calculation_type': 'db_direct',
        'source': 'jersey_number',
        'depends_on': [],
        'applies_to_entities': ['player'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': 35,
        'decimals': 0,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': False,
        'totals_mode_override': None,
    },
    'experience': {
        'key': 'experience',
        'display_name': 'EXP',
        'display_name_totals': 'EXP',
        'section': 'player_info',
        'subsection': None,
        'view_mode': 'both',
        'calculation_type': 'formula',
        'source': 'current_year - first_year',
        'depends_on': ['current_year', 'first_year'],
        'applies_to_entities': ['player'],
        'applies_to_periods': ['season'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 0,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': False,
        'totals_mode_override': None,
    },
    'age': {
        'key': 'age',
        'display_name': 'AGE',
        'display_name_totals': 'AGE',
        'section': 'player_info',
        'subsection': None,
        'view_mode': 'both',
        'calculation_type': 'function',
        'source': 'calculate_age(birthdate)',
        'depends_on': ['birthdate'],
        'applies_to_entities': ['player'],
        'applies_to_periods': ['season'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 0,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': False,
        'totals_mode_override': None,
    },
    'height': {
        'key': 'height',
        'display_name': 'HT',
        'display_name_totals': 'HT',
        'section': 'player_info',
        'subsection': None,
        'view_mode': 'both',
        'calculation_type': 'function',
        'source': 'format_measurement(height_inches)',
        'depends_on': ['height_inches'],
        'applies_to_entities': ['player'],
        'applies_to_periods': ['season'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 0,
        'is_percentage': False,
        'reverse_for_percentile': True,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'weight': {
        'key': 'weight',
        'display_name': 'WT',
        'display_name_totals': 'WT',
        'section': 'player_info',
        'subsection': None,
        'view_mode': 'both',
        'calculation_type': 'db_direct',
        'source': 'weight_lbs',
        'depends_on': [],
        'applies_to_entities': ['player'],
        'applies_to_periods': ['season'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 0,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'wingspan': {
        'key': 'wingspan',
        'display_name': 'WS',
        'display_name_totals': 'WS',
        'section': 'player_info',
        'subsection': None,
        'view_mode': 'both',
        'calculation_type': 'function',
        'source': 'format_measurement(wingspan_inches)',
        'depends_on': ['wingspan_inches'],
        'applies_to_entities': ['player'],
        'applies_to_periods': ['season'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 0,
        'is_percentage': False,
        'reverse_for_percentile': True,
        'editable': True,
        'has_percentile': True,
        'totals_mode_override': None,
    },

    # ========================================================================
    # ANALYSIS SECTION
    # ========================================================================
    'notes': {
        'key': 'notes',
        'display_name': 'Analysis',
        'display_name_totals': 'Analysis',
        'section': 'analysis',
        'subsection': None,
        'view_mode': 'both',
        'calculation_type': 'db_direct',
        'source': 'notes',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': 200,
        'decimals': 0,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': True,
        'has_percentile': False,
        'totals_mode_override': None,
    },

    # ========================================================================
    # RATES SECTION
    # ========================================================================
    'games': {
        'key': 'games',
        'display_name': 'GMS',
        'display_name_totals': 'GMS',
        'section': 'season',
        'subsection': 'rates',
        'view_mode': 'both',
        'calculation_type': 'db_direct',
        'source': 'games_played',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': 45,
        'decimals': 0,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': False,
        'totals_mode_override': None,
    },
    'minutes': {
        'key': 'minutes',
        'display_name': 'MIN',
        'display_name_totals': 'MIN',
        'section': 'season',
        'subsection': 'rates',
        'view_mode': 'both',
        'calculation_type': 'formula',
        'source': 'minutes_total / 10',
        'depends_on': ['minutes_total'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'possessions': {
        'key': 'possessions',
        'display_name': 'POS',
        'display_name_totals': 'POS',
        'section': 'season',
        'subsection': 'rates',
        'view_mode': 'both',
        'calculation_type': 'formula',
        'source': '(fg2a + fg3a) + 0.44 * fta + turnovers - off_rebounds',
        'depends_on': ['fg2a', 'fg3a', 'fta', 'turnovers', 'off_rebounds'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },

    # ========================================================================
    # SCORING SECTION (Part 1 - Basic Scoring)
    # ========================================================================
    'points': {
        'key': 'points',
        'display_name': 'PTS',
        'display_name_totals': 'PTS',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'both',
        'calculation_type': 'formula',
        'source': '2 * fg2m + 3 * fg3m + ftm',
        'depends_on': ['fg2m', 'fg3m', 'ftm'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': 50,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'ts_pct': {
        'key': 'ts_pct',
        'display_name': 'TS%',
        'display_name_totals': 'TS%',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'both',
        'calculation_type': 'formula',
        'source': '(points) / (2 * (fg2a + fg3a + 0.44 * fta)) * 100',
        'depends_on': ['points', 'fg2a', 'fg3a', 'fta'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': True,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'fg2a': {
        'key': 'fg2a',
        'display_name': '2PA',
        'display_name_totals': '2PA',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'both',
        'calculation_type': 'db_direct',
        'source': 'fg2a',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'fg2_pct': {
        'key': 'fg2_pct',
        'display_name': '2P%',
        'display_name_totals': '2P%',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'both',
        'calculation_type': 'formula',
        'source': 'fg2m / fg2a * 100',
        'depends_on': ['fg2m', 'fg2a'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': True,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'fg3a': {
        'key': 'fg3a',
        'display_name': '3PA',
        'display_name_totals': '3PA',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'both',
        'calculation_type': 'db_direct',
        'source': 'fg3a',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'fg3_pct': {
        'key': 'fg3_pct',
        'display_name': '3P%',
        'display_name_totals': '3P%',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'both',
        'calculation_type': 'formula',
        'source': 'fg3m / fg3a * 100',
        'depends_on': ['fg3m', 'fg3a'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': True,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },

    # ========================================================================
    # SCORING SECTION (Part 2 - Advanced Tracking)
    # ========================================================================
    'cont_rim_fga': {
        'key': 'cont_rim_fga',
        'display_name': 'CRA',
        'display_name_totals': 'CRA',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'advanced',
        'calculation_type': 'db_direct',
        'source': 'cont_rim_fga',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'cont_rim_pct': {
        'key': 'cont_rim_pct',
        'display_name': 'CR%',
        'display_name_totals': 'CR%',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'advanced',
        'calculation_type': 'formula',
        'source': 'cont_rim_fgm / cont_rim_fga * 100',
        'depends_on': ['cont_rim_fgm', 'cont_rim_fga'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': True,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'open_rim_fga': {
        'key': 'open_rim_fga',
        'display_name': 'ORA',
        'display_name_totals': 'ORA',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'advanced',
        'calculation_type': 'db_direct',
        'source': 'open_rim_fga',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'open_rim_pct': {
        'key': 'open_rim_pct',
        'display_name': 'OR%',
        'display_name_totals': 'OR%',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'advanced',
        'calculation_type': 'formula',
        'source': 'open_rim_fgm / open_rim_fga * 100',
        'depends_on': ['open_rim_fgm', 'open_rim_fga'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': True,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'cont_mid_fga': {
        'key': 'cont_mid_fga',
        'display_name': 'CMRA',
        'display_name_totals': 'CMRA',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'advanced',
        'calculation_type': 'formula',
        'source': 'cont_fg2a - cont_rim_fga',
        'depends_on': ['cont_fg2a', 'cont_rim_fga'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'cont_mid_pct': {
        'key': 'cont_mid_pct',
        'display_name': 'CMR%',
        'display_name_totals': 'CMR%',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'advanced',
        'calculation_type': 'formula',
        'source': '(cont_fg2m - cont_rim_fgm) / (cont_fg2a - cont_rim_fga) * 100',
        'depends_on': ['cont_fg2m', 'cont_fg2a', 'cont_rim_fgm', 'cont_rim_fga'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': True,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'open_mid_fga': {
        'key': 'open_mid_fga',
        'display_name': 'OMRA',
        'display_name_totals': 'OMRA',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'advanced',
        'calculation_type': 'formula',
        'source': 'open_fg2a - open_rim_fga',
        'depends_on': ['open_fg2a', 'open_rim_fga'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'open_mid_pct': {
        'key': 'open_mid_pct',
        'display_name': 'OMR%',
        'display_name_totals': 'OMR%',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'advanced',
        'calculation_type': 'formula',
        'source': '(open_fg2m - open_rim_fgm) / (open_fg2a - open_rim_fga) * 100',
        'depends_on': ['open_fg2m', 'open_fg2a', 'open_rim_fgm', 'open_rim_fga'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': True,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'cont_fg3a': {
        'key': 'cont_fg3a',
        'display_name': 'C3PA',
        'display_name_totals': 'C3PA',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'advanced',
        'calculation_type': 'db_direct',
        'source': 'cont_fg3a',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'cont_fg3_pct': {
        'key': 'cont_fg3_pct',
        'display_name': 'C3P%',
        'display_name_totals': 'C3P%',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'advanced',
        'calculation_type': 'formula',
        'source': 'cont_fg3m / cont_fg3a * 100',
        'depends_on': ['cont_fg3m', 'cont_fg3a'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': True,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'open_fg3a': {
        'key': 'open_fg3a',
        'display_name': 'O3PA',
        'display_name_totals': 'O3PA',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'advanced',
        'calculation_type': 'db_direct',
        'source': 'open_fg3a',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'open_fg3_pct': {
        'key': 'open_fg3_pct',
        'display_name': 'O3P%',
        'display_name_totals': 'O3P%',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'advanced',
        'calculation_type': 'formula',
        'source': 'open_fg3m / open_fg3a * 100',
        'depends_on': ['open_fg3m', 'open_fg3a'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': True,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'fta': {
        'key': 'fta',
        'display_name': 'FTA',
        'display_name_totals': 'FTA',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'both',
        'calculation_type': 'db_direct',
        'source': 'fta',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'ft_pct': {
        'key': 'ft_pct',
        'display_name': 'FT%',
        'display_name_totals': 'FT%',
        'section': 'season',
        'subsection': 'scoring',
        'view_mode': 'both',
        'calculation_type': 'formula',
        'source': 'ftm / fta * 100',
        'depends_on': ['ftm', 'fta'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': True,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },

    # ========================================================================
    # DISTRIBUTION SECTION
    # ========================================================================
    'touches': {
        'key': 'touches',
        'display_name': 'TOU',
        'display_name_totals': 'TOU',
        'section': 'season',
        'subsection': 'distribution',
        'view_mode': 'advanced',
        'calculation_type': 'db_direct',
        'source': 'touches',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': 50,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'assists': {
        'key': 'assists',
        'display_name': 'AST',
        'display_name_totals': 'AST',
        'section': 'season',
        'subsection': 'distribution',
        'view_mode': 'both',
        'calculation_type': 'db_direct',
        'source': 'assists',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'pot_assists': {
        'key': 'pot_assists',
        'display_name': 'PAST',
        'display_name_totals': 'PAST',
        'section': 'season',
        'subsection': 'distribution',
        'view_mode': 'advanced',
        'calculation_type': 'db_direct',
        'source': 'pot_ast',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'turnovers': {
        'key': 'turnovers',
        'display_name': 'TOV',
        'display_name_totals': 'TOV',
        'section': 'season',
        'subsection': 'distribution',
        'view_mode': 'both',
        'calculation_type': 'db_direct',
        'source': 'turnovers',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': True,  # Lower is better
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },

    # ========================================================================
    # REBOUNDING SECTION
    # ========================================================================
    'oreb_pct': {
        'key': 'oreb_pct',
        'display_name': 'ORB%',
        'display_name_totals': 'ORB',  # Totals mode shows raw count
        'section': 'season',
        'subsection': 'rebounding',
        'view_mode': 'both',
        'calculation_type': 'formula',
        'source': 'off_reb_pct_x1000 / 1000',  # Unscale from x1000
        'depends_on': ['off_reb_pct_x1000'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['per_game', 'per_100', 'per_36'],
        'width': 50,
        'decimals': 1,
        'is_percentage': True,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': {'display_name': 'ORB', 'source': 'cont_off_rebs', 'decimals': 0, 'is_percentage': False},
    },
    'dreb_pct': {
        'key': 'dreb_pct',
        'display_name': 'DRB%',
        'display_name_totals': 'DRB',
        'section': 'season',
        'subsection': 'rebounding',
        'view_mode': 'both',
        'calculation_type': 'formula',
        'source': 'def_reb_pct_x1000 / 1000',
        'depends_on': ['def_reb_pct_x1000'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': True,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': {'display_name': 'DRB', 'source': 'cont_def_rebs', 'decimals': 0, 'is_percentage': False},
    },
    'cont_oreb_pct': {
        'key': 'cont_oreb_pct',
        'display_name': 'COR%',
        'display_name_totals': 'COR',
        'section': 'season',
        'subsection': 'rebounding',
        'view_mode': 'advanced',
        'calculation_type': 'formula',
        'source': 'cont_off_rebs / off_rebounds * 100',
        'depends_on': ['cont_off_rebs', 'off_rebounds'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': True,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': {'display_name': 'CORB', 'source': 'cont_off_rebs', 'decimals': 0, 'is_percentage': False},
    },
    'cont_dreb_pct': {
        'key': 'cont_dreb_pct',
        'display_name': 'CDR%',
        'display_name_totals': 'CDR',
        'section': 'season',
        'subsection': 'rebounding',
        'view_mode': 'advanced',
        'calculation_type': 'formula',
        'source': 'cont_def_rebs / def_rebounds * 100',
        'depends_on': ['cont_def_rebs', 'def_rebounds'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': True,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': {'display_name': 'CDRB', 'source': 'cont_def_rebs', 'decimals': 0, 'is_percentage': False},
    },
    'putbacks': {
        'key': 'putbacks',
        'display_name': 'PBS',
        'display_name_totals': 'PBS',
        'section': 'season',
        'subsection': 'rebounding',
        'view_mode': 'advanced',
        'calculation_type': 'db_direct',
        'source': 'putbacks',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },

    # ========================================================================
    # DEFENSE SECTION
    # ========================================================================
    'def_rim_fga': {
        'key': 'def_rim_fga',
        'display_name': 'DRA',
        'display_name_totals': 'DRA',
        'section': 'season',
        'subsection': 'defense',
        'view_mode': 'advanced',
        'calculation_type': 'db_direct',
        'source': 'def_rim_fga',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': 50,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'def_rim_pct': {
        'key': 'def_rim_pct',
        'display_name': 'DR%',
        'display_name_totals': 'DR%',
        'section': 'season',
        'subsection': 'defense',
        'view_mode': 'advanced',
        'calculation_type': 'formula',
        'source': 'def_rim_fgm / def_rim_fga * 100',
        'depends_on': ['def_rim_fgm', 'def_rim_fga'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': True,
        'reverse_for_percentile': True,  # Lower is better for defense
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'def_mid_fga': {
        'key': 'def_mid_fga',
        'display_name': 'DMRA',
        'display_name_totals': 'DMRA',
        'section': 'season',
        'subsection': 'defense',
        'view_mode': 'advanced',
        'calculation_type': 'formula',
        'source': 'def_fg2a - def_rim_fga',
        'depends_on': ['def_fg2a', 'def_rim_fga'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'def_mid_pct': {
        'key': 'def_mid_pct',
        'display_name': 'DMR%',
        'display_name_totals': 'DMR%',
        'section': 'season',
        'subsection': 'defense',
        'view_mode': 'advanced',
        'calculation_type': 'formula',
        'source': '(def_fg2m - def_rim_fgm) / (def_fg2a - def_rim_fga) * 100',
        'depends_on': ['def_fg2m', 'def_fg2a', 'def_rim_fgm', 'def_rim_fga'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': True,
        'reverse_for_percentile': True,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'def_fg3a': {
        'key': 'def_fg3a',
        'display_name': 'D3PA',
        'display_name_totals': 'D3PA',
        'section': 'season',
        'subsection': 'defense',
        'view_mode': 'advanced',
        'calculation_type': 'db_direct',
        'source': 'def_fg3a',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'def_fg3_pct': {
        'key': 'def_fg3_pct',
        'display_name': 'D3P%',
        'display_name_totals': 'D3P%',
        'section': 'season',
        'subsection': 'defense',
        'view_mode': 'advanced',
        'calculation_type': 'formula',
        'source': 'def_fg3_fgm / def_fg3a * 100',
        'depends_on': ['def_fg3_fgm', 'def_fg3a'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': True,
        'reverse_for_percentile': True,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'real_def_pct': {
        'key': 'real_def_pct',
        'display_name': 'RD%',
        'display_name_totals': 'RD%',
        'section': 'season',
        'subsection': 'defense',
        'view_mode': 'advanced',
        'calculation_type': 'formula',
        'source': 'real_def_fg_pct_x1000 / 1000',
        'depends_on': ['real_def_fg_pct_x1000'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': True,
        'reverse_for_percentile': True,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'steals': {
        'key': 'steals',
        'display_name': 'STL',
        'display_name_totals': 'STL',
        'section': 'season',
        'subsection': 'defense',
        'view_mode': 'both',
        'calculation_type': 'db_direct',
        'source': 'steals',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'deflections': {
        'key': 'deflections',
        'display_name': 'DEF',
        'display_name_totals': 'DEF',
        'section': 'season',
        'subsection': 'defense',
        'view_mode': 'advanced',
        'calculation_type': 'db_direct',
        'source': 'deflections',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'blocks': {
        'key': 'blocks',
        'display_name': 'BLK',
        'display_name_totals': 'BLK',
        'section': 'season',
        'subsection': 'defense',
        'view_mode': 'both',
        'calculation_type': 'db_direct',
        'source': 'blocks',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'contests': {
        'key': 'contests',
        'display_name': 'CON',
        'display_name_totals': 'CON',
        'section': 'season',
        'subsection': 'defense',
        'view_mode': 'advanced',
        'calculation_type': 'db_direct',
        'source': 'contests',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'charges': {
        'key': 'charges',
        'display_name': 'CHG',
        'display_name_totals': 'CHG',
        'section': 'season',
        'subsection': 'defense',
        'view_mode': 'advanced',
        'calculation_type': 'db_direct',
        'source': 'charges_drawn',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'fouls': {
        'key': 'fouls',
        'display_name': 'FLS',
        'display_name_totals': 'FLS',
        'section': 'season',
        'subsection': 'defense',
        'view_mode': 'both',
        'calculation_type': 'db_direct',
        'source': 'fouls',
        'depends_on': [],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': True,  # Lower is better
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },

    # ========================================================================
    # ON/OFF SECTION
    # ========================================================================
    'off_rating': {
        'key': 'off_rating',
        'display_name': 'OR',
        'display_name_totals': 'OR',
        'section': 'season',
        'subsection': 'onoff',
        'view_mode': 'both',
        'calculation_type': 'formula',
        'source': 'off_rating_x10 / 10',
        'depends_on': ['off_rating_x10'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': 50,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'def_rating': {
        'key': 'def_rating',
        'display_name': 'DR',
        'display_name_totals': 'DR',
        'section': 'season',
        'subsection': 'onoff',
        'view_mode': 'both',
        'calculation_type': 'formula',
        'source': 'def_rating_x10 / 10',
        'depends_on': ['def_rating_x10'],
        'applies_to_entities': ['player', 'team'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': True,  # Lower is better for defense
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'off_court_team_off_rating': {
        'key': 'off_court_team_off_rating',
        'display_name': 'OTOR',
        'display_name_totals': 'OTOR',
        'section': 'season',
        'subsection': 'onoff',
        'view_mode': 'advanced',
        'calculation_type': 'formula',
        'source': 'off_court_team_off_rating_x10 / 10',
        'depends_on': ['off_court_team_off_rating_x10'],
        'applies_to_entities': ['player'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },
    'off_court_team_def_rating': {
        'key': 'off_court_team_def_rating',
        'display_name': 'OTDR',
        'display_name_totals': 'OTDR',
        'section': 'season',
        'subsection': 'onoff',
        'view_mode': 'advanced',
        'calculation_type': 'formula',
        'source': 'off_court_team_def_rating_x10 / 10',
        'depends_on': ['off_court_team_def_rating_x10'],
        'applies_to_entities': ['player'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': None,
        'decimals': 1,
        'is_percentage': False,
        'reverse_for_percentile': True,
        'editable': False,
        'has_percentile': True,
        'totals_mode_override': None,
    },

    # ========================================================================
    # IDENTITY SECTION
    # ========================================================================
    'player_id': {
        'key': 'player_id',
        'display_name': 'ID',
        'display_name_totals': 'ID',
        'section': 'identity',
        'subsection': None,
        'view_mode': 'both',
        'calculation_type': 'db_direct',
        'source': 'player_id',
        'depends_on': [],
        'applies_to_entities': ['player'],
        'applies_to_periods': ['season', 'historical', 'postseason'],
        'applies_to_modes': ['totals', 'per_game', 'per_100', 'per_36'],
        'width': 80,
        'decimals': 0,
        'is_percentage': False,
        'reverse_for_percentile': False,
        'editable': False,
        'has_percentile': False,
        'totals_mode_override': None,
    },
}


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def get_display_columns_by_section(section):
    """Get all display columns for a specific section."""
    return {k: v for k, v in DISPLAY_COLUMNS.items() if v['section'] == section}


def get_display_columns_by_view(view_mode):
    """
    Get display columns for a specific view mode.
    Args:
        view_mode: 'basic', 'advanced', or 'both'
    """
    if view_mode == 'both':
        return DISPLAY_COLUMNS
    return {k: v for k, v in DISPLAY_COLUMNS.items() 
            if v['view_mode'] in [view_mode, 'both']}


def get_display_columns_by_entity(entity_type):
    """Get display columns applicable to an entity type."""
    return {k: v for k, v in DISPLAY_COLUMNS.items() 
            if entity_type in v['applies_to_entities']}


def get_display_columns_by_period(period):
    """Get display columns applicable to a period."""
    return {k: v for k, v in DISPLAY_COLUMNS.items() 
            if period in v['applies_to_periods']}


def get_editable_columns():
    """Get all editable columns (notes, wingspan)."""
    return {k: v for k, v in DISPLAY_COLUMNS.items() if v['editable']}


def generate_percentile_columns():
    """
    Auto-generate percentile column definitions for all columns with has_percentile=True.
    Percentiles are ALWAYS calculated for the current stats mode and separated by entity type.
    
    Returns a dictionary of percentile columns in the format:
    - {col_key}_pct_player: Percentile among all players
    - {col_key}_pct_team: Percentile for team row (among all teams)
    - {col_key}_pct_opponent: Percentile for opponent row (among all teams)
    """
    percentile_columns = {}
    
    for col_key, col_def in DISPLAY_COLUMNS.items():
        if not col_def['has_percentile']:
            continue
        
        # Determine which entity types this stat applies to
        entities = col_def['applies_to_entities']
        
        # Generate percentile columns for each applicable entity type
        for entity in entities:
            pct_key = f"{col_key}_pct_{entity}"
            
            percentile_columns[pct_key] = {
                'key': pct_key,
                'display_name': f"{col_def['display_name']}%",
                'display_name_totals': f"{col_def['display_name_totals']}%",
                'section': col_def['section'],
                'subsection': col_def['subsection'],
                'view_mode': col_def['view_mode'],
                'calculation_type': 'percentile',
                'source': f"percentile({col_key}, {entity})",
                'depends_on': [col_key],
                'applies_to_entities': [entity],
                'applies_to_periods': col_def['applies_to_periods'],
                'applies_to_modes': col_def['applies_to_modes'],
                'applies_to_sheets': col_def['applies_to_sheets'],
                'hidden_in_sheets': col_def.get('hidden_in_sheets', []),
                'width': None,
                'decimals': 1,
                'is_percentage': True,
                'reverse_for_percentile': col_def['reverse_for_percentile'],
                        'editable': False,
                'has_percentile': False,  # Percentiles don't have percentiles
                'totals_mode_override': None,
                'is_generated_percentile': True,
                'base_stat': col_key,
                'percentile_entity': entity,
            }
    
    return percentile_columns


def get_all_columns_with_percentiles():
    """Get DISPLAY_COLUMNS plus all auto-generated percentile columns."""
    all_cols = dict(DISPLAY_COLUMNS)
    all_cols.update(generate_percentile_columns())
    return all_cols

