"""
The Glass - Column Registry

Single source of truth for database schema and column definitions.
Column names match the actual PostgreSQL schema exactly.

Provider-specific source mappings (how to fetch each column from an API)
live in each provider module (e.g., src/input/sources/nba_api/sources.py).

Transforms are inferred from column type unless overridden:
  SMALLINT / INTEGER -> safe_int
  VARCHAR / TEXT / CHAR -> safe_str
"""

from typing import Any, Dict


# ============================================================================
# DEFAULT TRANSFORMS BY COLUMN TYPE
# ============================================================================

TYPE_TRANSFORMS = {
    'SMALLINT': 'safe_int',
    'INTEGER': 'safe_int',
    'VARCHAR': 'safe_str',
    'TEXT': 'safe_str',
    'CHAR': 'safe_str',
}


# ============================================================================
# TABLE DEFINITIONS
# ============================================================================

TABLES = {
    'players': {
        'entity': 'player',
        'scope': 'entity',
        'unique_key': ['nba_api_id'],
    },
    'teams': {
        'entity': 'team',
        'scope': 'entity',
        'unique_key': ['nba_api_id'],
    },
    'player_season_stats': {
        'entity': 'player',
        'scope': 'stats',
        'unique_key': ['nba_api_id', 'season', 'season_type'],
    },
    'team_season_stats': {
        'entity': 'team',
        'scope': 'stats',
        'unique_key': ['nba_api_id', 'season', 'season_type'],
        'has_opponent_columns': True,
    },
}


# ============================================================================
# COLUMN REGISTRY
# ============================================================================

DB_COLUMNS: Dict[str, Dict[str, Any]] = {

    # ------------------------------------------------------------------
    # SYSTEM COLUMNS  (managed by DB / ETL engine, no provider sources)
    # ------------------------------------------------------------------
    'id': {
        'type': 'SERIAL',
        'scope': ['entity', 'stats'],
        'nullable': False,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': None,
        'rate_group': None,
        'comment': None,
        'primary_key': True,
    },
    'nba_api_id': {
        'type': 'VARCHAR(10)',
        'scope': ['entity', 'stats'],
        'nullable': False,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': None,
        'rate_group': None,
        'comment': None,
    },
    'updated_at': {
        'type': 'TIMESTAMP',
        'scope': ['entity', 'stats'],
        'nullable': True,
        'default': 'CURRENT_TIMESTAMP',
        'entity_types': ['player', 'team'],
        'update_frequency': None,
        'rate_group': None,
        'comment': None,
    },
    'created_at': {
        'type': 'TIMESTAMP',
        'scope': ['entity'],
        'nullable': True,
        'default': 'CURRENT_TIMESTAMP',
        'entity_types': ['player', 'team'],
        'update_frequency': None,
        'rate_group': None,
        'comment': None,
    },
    'season': {
        'type': 'VARCHAR(7)',
        'scope': ['stats'],
        'nullable': False,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': None,
        'rate_group': None,
        'comment': None,
    },
    'season_type': {
        'type': 'VARCHAR(3)',
        'scope': ['stats'],
        'nullable': False,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': None,
        'rate_group': None,
        'comment': None,
    },
    'backfilled': {
        'type': 'BOOLEAN',
        'scope': ['entity'],
        'nullable': False,
        'default': 'FALSE',
        'entity_types': ['player', 'team'],
        'update_frequency': None,
        'rate_group': None,
        'comment': None,
    },
    'notes': {
        'type': 'TEXT',
        'scope': ['entity'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': None,
        'rate_group': None,
        'comment': None,
    },
    # ------------------------------------------------------------------
    # ENTITY INFORMATION  (player / team profile data)
    # ------------------------------------------------------------------
    'team_id': {
        'type': 'INTEGER',
        'scope': ['entity'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'name': {
        'type': 'VARCHAR(100)',
        'scope': ['entity'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'annual',
        'rate_group': None,
        'comment': None,
    },
    'height_ins': {
        'type': 'SMALLINT',
        'scope': ['entity'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'annual',
        'rate_group': None,
        'comment': None,
    },
    'weight_lbs': {
        'type': 'SMALLINT',
        'scope': ['entity'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'annual',
        'rate_group': None,
        'comment': None,
    },
    'wingspan_ins': {
        'type': 'SMALLINT',
        'scope': ['entity'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': None,
        'rate_group': None,
        'comment': None,
    },
    'jersey_num': {
        'type': 'VARCHAR(3)',
        'scope': ['entity'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'birthdate': {
        'type': 'DATE',
        'scope': ['entity'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'annual',
        'rate_group': None,
        'comment': None,
    },
    'hand': {
        'type': 'CHAR',
        'scope': ['entity'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': None,
        'rate_group': None,
        'comment': None,
    },
    'seasons_exp': {
        'type': 'SMALLINT',
        'scope': ['entity'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'rookie_season': {
        'type': 'VARCHAR(10)',
        'scope': ['entity'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'annual',
        'rate_group': None,
        'comment': None,
    },
    'abbr': {
        'type': 'VARCHAR(5)',
        'scope': ['entity'],
        'nullable': True,
        'default': None,
        'entity_types': ['team'],
        'update_frequency': 'annual',
        'rate_group': None,
        'comment': None,
    },
    'conf': {
        'type': 'VARCHAR(50)',
        'scope': ['entity'],
        'nullable': True,
        'default': None,
        'entity_types': ['team'],
        'update_frequency': 'annual',
        'rate_group': None,
        'comment': None,
    },
    # ------------------------------------------------------------------
    # GAMES & MINUTES
    # ------------------------------------------------------------------
    'games': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': False,
        'default': '0',
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'minutes_x10': {
        'type': 'INTEGER',
        'scope': ['stats'],
        'nullable': False,
        'default': '0',
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'wins': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'tr_games': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': False,
        'default': '0',
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'tr_minutes_x10': {
        'type': 'INTEGER',
        'scope': ['stats'],
        'nullable': False,
        'default': '0',
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'h_games': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': False,
        'default': '0',
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'hustle',
        'comment': None,
    },
    'h_minutes_x10': {
        'type': 'INTEGER',
        'scope': ['stats'],
        'nullable': False,
        'default': '0',
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'hustle',
        'comment': None,
    },
    'off_games': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': False,
        'default': '0',
        'entity_types': ['player'],
        'update_frequency': 'daily',
        'rate_group': 'onoff',
        'comment': None,
    },
    'off_minutes_x10': {
        'type': 'INTEGER',
        'scope': ['stats'],
        'nullable': False,
        'default': '0',
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'onoff',
        'comment': None,
    },
    # ------------------------------------------------------------------
    # SCORING: 2-POINT
    # ------------------------------------------------------------------
    'fg2m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'fg2a': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    # ------------------------------------------------------------------
    # SCORING: 3-POINT
    # ------------------------------------------------------------------
    'fg3m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'fg3a': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    # ------------------------------------------------------------------
    # SCORING: FREE THROWS
    # ------------------------------------------------------------------
    'ftm': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'fta': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    # ------------------------------------------------------------------
    # SHOT TRACKING: CONTESTED / OPEN  x  RIM / ALL
    # ------------------------------------------------------------------
    'cont_rim_fgm': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'cont_rim_fga': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'open_rim_fgm': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'open_rim_fga': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'cont_fg2m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'cont_fg2a': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'open_fg2m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'open_fg2a': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'cont_fg3m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'cont_fg3a': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'open_fg3m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'open_fg3a': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    # ------------------------------------------------------------------
    # PUTBACKS & DUNKS  (pipeline: filter shooting splits -> aggregate)
    # ------------------------------------------------------------------
    'putbacks': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'dunks': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    # ------------------------------------------------------------------
    # UNASSISTED FIELD GOALS  (per-player shooting splits)
    # ------------------------------------------------------------------
    'unassisted_rim_fgm': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'unassisted_fg2m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'unassisted_fg3m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    # ------------------------------------------------------------------
    # REBOUNDS
    # ------------------------------------------------------------------
    'o_rebs': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'd_rebs': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'o_reb_pct_x1000': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'd_reb_pct_x1000': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'cont_o_rebs': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'cont_d_rebs': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    # ------------------------------------------------------------------
    # PLAYMAKING
    # ------------------------------------------------------------------
    'assists': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'pot_assists': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'passes': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'sec_assists': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    # ------------------------------------------------------------------
    # BALL HANDLING
    # ------------------------------------------------------------------
    'touches': {
        'type': 'INTEGER',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'time_on_ball': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'possessions': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    # ------------------------------------------------------------------
    # TURNOVERS
    # ------------------------------------------------------------------
    'turnovers': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    # ------------------------------------------------------------------
    # DISTANCE
    # ------------------------------------------------------------------
    'o_dist_x10': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'd_dist_x10': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    # ------------------------------------------------------------------
    # DEFENSE: STEALS / BLOCKS / FOULS
    # ------------------------------------------------------------------
    'steals': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'blocks': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'fouls': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team', 'opponent'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    # ------------------------------------------------------------------
    # HUSTLE STATS
    # ------------------------------------------------------------------
    'deflections': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'hustle',
        'comment': None,
    },
    'charges_drawn': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'hustle',
        'comment': None,
    },
    'contests': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'hustle',
        'comment': None,
    },
    # ------------------------------------------------------------------
    # DEFENSIVE SHOT TRACKING  (leaguedashptdefend / leaguedashptteamdefend)
    # ------------------------------------------------------------------
    'd_rim_fgm': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'd_rim_fga': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'd_fg2m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'd_fg2a': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'd_fg3m': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'd_fg3a': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    # ------------------------------------------------------------------
    # RATINGS
    # ------------------------------------------------------------------
    'o_rtg_x10': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'd_rtg_x10': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': None,
        'comment': None,
    },
    'off_o_rtg_x10': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'daily',
        'rate_group': 'onoff',
        'comment': None,
    },
    'off_d_rtg_x10': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player'],
        'update_frequency': 'daily',
        'rate_group': 'onoff',
        'comment': None,
    },
    # ------------------------------------------------------------------
    # DEFENSIVE REAL FG% DIFFERENTIALS
    # ------------------------------------------------------------------
    'real_d_fg_pct_x1000': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'real_d_rim_fg_pct_x1000': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'real_d_fg2_pct_x1000': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
    'real_d_fg3_pct_x1000': {
        'type': 'SMALLINT',
        'scope': ['stats'],
        'nullable': True,
        'default': None,
        'entity_types': ['player', 'team'],
        'update_frequency': 'daily',
        'rate_group': 'tracking',
        'comment': None,
    },
}

