name: Daily Player Updates

on:
  schedule:
    # Runs at 5:00 AM UTC every day
    - cron: '0 5 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-players:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Update Players
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          python update_players_daily.py
      
      - name: Notify on failure
        if: failure()
        run: |
          echo "Player update failed at $(date)"
          # Add notification logic here (e.g., send email, Slack message)
