name: The Glass ETL Pipeline

on:
  schedule:
    # Run every day at 8 AM UTC year-round (includes Summer League!)
    # Note: GitHub Actions cron uses UTC time
    - cron: '0 8 * * *'
  
  workflow_dispatch:
    # Allow manual trigger any time of year
    inputs:
      start_date:
        description: 'Start date (YYYY-MM-DD) for backfill'
        required: false
        type: string
      end_date:
        description: 'End date (YYYY-MM-DD) for backfill'
        required: false
        type: string

jobs:
  etl:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run ETL Pipeline
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          START_DATE: ${{ github.event.inputs.start_date }}
          END_DATE: ${{ github.event.inputs.end_date }}
        run: |
          python etl_pipeline.py
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: etl-logs-${{ github.run_number }}
          path: etl_pipeline.log
          retention-days: 30
