name: Monthly Full Player Refresh

on:
  schedule:
    # Runs at 3:00 AM UTC on the 1st of every month
    - cron: '0 3 1 * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  populate-players:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Full Player Population
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          python populate_players.py
      
      - name: Notify on failure
        if: failure()
        run: |
          echo "Monthly player refresh failed at $(date)"
          # Add notification logic here (e.g., send email, Slack message)
