"""
The Glass - Unified Columns Configuration

Single source of truth for every column across all leagues.
"""

from typing import Any, Dict
from sheets.core.config import WIDTH_CLASSES

# ============================================================================
# COLUMN DEFINITIONS
# ============================================================================

SHEETS_COLUMNS: Dict[str, Any] = {
    'names': {
        'stat_category': 'none',
        'display_name': None,
        'description': 'Team / Player Names',
        'section': ['entities'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'text',
        'decimal_places': 0,
        'width_class': 'auto',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': None,
        'nullable': True,
        'formulas': {
            'player': 'name',
            'team': 'TEAM',
            'opponents': 'OPPONENTS',
        },
    },
    'team': {
        'stat_category': 'none',
        'display_name': 'Tm',
        'description': 'team abbreviation',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_players'],
        'stat_mode': 'both',
        'has_percentile': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'text',
        'decimal_places': 0,
        'width_class': 'two_',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': None,
        'nullable': True,
        'formulas': {
            'player': 'abbr',
        }
    },
    'jersey': {
        'stat_category': 'none',
        'display_name': '#',
        'description': 'jersey number',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'width_class': 'two_char',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': None,
        'nullable': True,
        'formulas': {
            'player': 'jersey_number',
        }
    },
    'experience': {
        'stat_category': 'none',
        'display_name': 'Exp',
        'description': None,
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'average',
        'nullable': False,
        'formulas': {
            'player': 'years_experience',
            'team': 'years_experience',
        }
    },
    'age': {
        'stat_category': 'none',
        'display_name': 'Age',
        'description': 'player age',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'average',
        'nullable': False,
        'formulas': {
                'player': 'age',
        },
    },
    'height': {
        'stat_category': 'none',
        'display_name': 'Ht',
        'description': 'height',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'height',
        'decimal_places': 1,
        'width_class': 'measurement',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'average',
        'nullable': False,
        'formulas': {
            'player': 'height_inches',
            'team': 'height_inches',
        }
    },
    'weight': {
        'stat_category': 'none',
        'display_name': 'Wt',
        'description': 'weight',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'average',
        'nullable': False,
        'formulas': {
            'player': 'weight_lbs',
            'team': 'weight_lbs',
        }
    },
    'wingspan': {
        'stat_category': 'none',
        'display_name': 'WS',
        'description': 'wingspan',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': True,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'height',
        'decimal_places': 1,
        'width_class': 'measurement',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'average',
        'nullable': False,
        'formulas': {
            'player': 'wingspan_inches',
            'team': 'wingspan_inches',
        }
    },
    'hand': {
        'stat_category': 'none',
        'display_name': '🖐️',
        'description': 'handedness',
        'section': ['player_info'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': False,
        'editable': True,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'width_class': 'two_char',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': None,
        'nullable': False,
        'formulas': {
            'player': 'hand',
        }
    },
    'notes': {
        'stat_category': 'none',
        'display_name': 'Notes',
        'description': 'Scouting notes (editable)',
        'section': ['analysis'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': False,
        'editable': True,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'width_class': 'auto',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': None,
        'nullable': False,
        'formulas': {
            'player': 'notes',
            'team': 'notes',
        }
    },
    'years': {
        'stat_category': 'none',
        'display_name': 'Yrs',
        'description': 'Number of seasons in range',
        'section': ['historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': 'season',
            'team': 'season',
        }
    },
    'games': {
        'stat_category': 'none',
        'display_name': 'GMS',
        'description': 'Games played',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': 'games / years',
            'team': 'games / years',
        },
    },
    'minutes': {
        'stat_category': 'none',
        'display_name': 'Min',
        'description': 'Minutes played',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': 'per_game_only',
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': 'minutes_x10 / 10',
            'team': 'minutes_x10 / 10',
        }
    },
    'pace': {
        'stat_category': 'basic',
        'display_name': 'Pace',
        'description': None,
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': '(48 / (minutes_x10 / 10)) * possessions',
            'team': '(48 / (minutes_x10 / 10)) * possessions',
        }
    },
    'points': {
        'stat_category': 'basic',
        'display_name': 'PTS',
        'description': 'Total points scored',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': '(2fgm * 2) + (3fgm * 3) + ftm',
            'team': '(2fgm * 2) + (3fgm * 3) + ftm',
            'opponents': '(opp_2fgm * 2) + (opp_3fgm * 3) + opp_ftm',
        }
    },
    'true_points_per_shot_attempt': {
        'stat_category': 'basic',
        'display_name': 'TPS',
        'description': 'Points per true shot attempt (2FGA + 3FGA + 0.44*FTA)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': '((2fgm * 2) + (3fgm * 3) + ftm) / (2fga + 3fga + 0.44 * fta)',
            'team': '((2fgm * 2) + (3fgm * 3) + ftm) / (2fga + 3fga + 0.44 * fta)',
            'opponents': '((opp_2fgm * 2) + (opp_3fgm * 3) + opp_ftm) / (opp_2fga + opp_3fga + 0.44 * opp_fta)',
        }
    },
    '2fga': {
        'stat_category': 'basic',
        'display_name': '2A',
        'description': 'Two-point field goal attempts',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': '2fga',
            'team': '2fga',
            'opponents': 'opp_2fga',
        }
    },
    'Points_Per_Two_attempt': {
        'stat_category': 'basic',
        'display_name': 'P2',
        'description': 'Points per two-point attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': '2 * (2fgm / 2fga)',
            'team': '2 * (2fgm / 2fga)',
            'opponents': '2 * (opp_2fgm / opp_2fga)',
        }
    },
    'cont_close_2fga': {
        'stat_category': 'tracking',
        'display_name': 'CC2A',
        'description': 'Contested close two-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'cont_close_2fga',
        },
    },
    'Points_Per_cont_close_2fga': {
        'stat_category': 'tracking',
        'display_name': 'PCC2',
        'description': 'Points per contested close two attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': '2 * (cont_close_2fgm / cont_close_2fga)',
        },
    },
    'open_close_2fga': {
        'stat_category': 'tracking',
        'display_name': 'OC2A',
        'description': 'Open close two-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'open_close_2fga',
        },
    },
    'Points_Per_open_close_2fga': {
        'stat_category': 'tracking',
        'display_name': 'POC2',
        'description': 'Points per open close two attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': '2 * (open_close_2fgm / open_close_2fga)',
        },
    },
    'cont_long_2fga': {
        'stat_category': 'tracking',
        'display_name': 'CL2A',
        'description': 'Contested long two-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'cont_2fga - cont_close_2fga',
        },
    },
    'points_per_cont_long_2fga': {
        'stat_category': 'tracking',
        'display_name': 'PCL2',
        'description': 'Points per contested long two attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': '2 * ((cont_2fgm - cont_close_2fgm) / (cont_2fga - cont_close_2fga))',
        },
    },
    'open_long_2fga': {
        'stat_category': 'tracking',
        'display_name': 'OL2A',
        'description': 'Open long two-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'open_2fga - open_close_2fga',
        },
    },
    'points_per_open_long_2fga': {
        'stat_category': 'tracking',
        'display_name': 'POL2',
        'description': 'Points per open long two attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': '2* ((open_2fgm - open_close_2fgm) / (open_2fga - open_close_2fga))',
        },
    },
    '3fga': {
        'stat_category': 'basic',
        'display_name': '3A',
        'description': 'Three-point field goal attempts',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': '3fga',
            'team': '3fga',
            'opponents': 'opp_3fga',
        }
    },
    'Points_Per_Three_attempt': {
        'stat_category': 'basic',
        'display_name': 'P3',
        'description': 'Points per three-point attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': '3 * (3fgm / 3fga)',
            'team': '3 * (3fgm / 3fga)',
            'opponents': '3 * (opp_3fgm / opp_3fga)',
        }
    },
    'cont_3fga': {
        'stat_category': 'tracking',
        'display_name': 'C3A',
        'description': 'Contested three-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'cont_3fga',
        },
    },
    'points_per_cont_3fga': {
        'stat_category': 'tracking',
        'display_name': 'PC3',
        'description': 'Points per contested three attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': '3 * (cont_3fgm / cont_3fga)',
        },
    },
    'open_3fga': {
        'stat_category': 'tracking',
        'display_name': 'O3A',
        'description': 'Open three-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'open_3fga',
        },
    },
    'points_per_open_3fga': {
        'stat_category': 'tracking',
        'display_name': 'PO3',
        'description': 'Points per open three attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': '3 * (open_3fgm / open_3fga)',
        },
    },
    'free_throw_rate': {
        'stat_category': 'basic',
        'display_name': 'FTR',
        'description': 'Free throw attempts per field goal attempt',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': 'fta / (2fga + 3fga)',
            'team': 'fta / (2fga + 3fga)',
            'opponents': 'opp_fta / (opp_2fga + opp_3fga)',
        }
    },
    'points_per_ft': {
        'stat_category': 'basic',
        'display_name': 'PFT',
        'description': 'Points per free throw',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': 'ftm / fta',
            'team': 'ftm / fta',
            'opponents': 'opp_ftm / opp_fta',
        }
    },
    'dunks': {
        'stat_category': 'tracking',
        'display_name': 'Dnk',
        'description': 'Dunks',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'scoring',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'dunks',
        },
    },
    'assists': {
        'stat_category': 'basic',
        'display_name': 'AST',
        'description': None,
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': 'assists',
            'team': 'assists',
            'opponents': 'opp_assists',
        }
    },
    'potential_assists': {
        'stat_category': 'tracking',
        'display_name': 'PAST',
        'description': 'Potential assists (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'pot_assists',
        },
    },
    'secondary_assists': {
        'stat_category': 'tracking',
        'display_name': '2AST',
        'description': 'Secondary assists (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'sec_assists',
        },
    },
    'passes': {
        'stat_category': 'tracking',
        'display_name': 'Pass',
        'description': 'Total passes made (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'passes',
        },
    },
    'touches': {
        'stat_category': 'tracking',
        'display_name': 'Tou',
        'description': 'Total touches (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'touches',
        },
    },
    'seconds_per_touch': {
        'stat_category': 'tracking',
        'display_name': 'SPT',
        'description': 'Average seconds per touch (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': '(60 * time_on_ball) / touches',
        },
    },
    'dribbles_per_touch': {
        'stat_category': 'tracking',
        'display_name': 'DPT',
        'description': 'Average dribbles per touch (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'dribbles / touches',
        },
    },
    'pct_touches_shots': {
        'stat_category': 'tracking',
        'display_name': '%TS',
        'description': 'Percentage of touches that result in a shot (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': '((2fga + 3fga + (0.44 * fta)) / touches) * 100',
        },
    },
    'pct_touches_passes': {
        'stat_category': 'tracking',
        'display_name': '%TP',
        'description': 'Percentage of touches that result in a pass (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': '(passes / touches) * 100',
        },
    },
    'pct_touches_turnovers': {
        'stat_category': 'tracking',
        'display_name': '%TT',
        'description': 'Percentage of touches that result in a turnover (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': '(turnovers / touches) * 100',
        },
    },
    'turnovers': {
        'stat_category': 'basic',
        'display_name': 'TOV',
        'description': 'Turnovers',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'ball_management',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': 'turnovers',
            'team': 'turnovers',
            'opponents': 'opp_turnovers',
        }
    },
    'oreb_pct': {
        'stat_category': 'basic',
        'display_name': 'OR%',
        'description': 'Offensive rebound percentage',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': 'o_rebound_pct_x1000 / 10',
            'team': 'o_rebound_pct_x1000 / 10',
        }
    },
    'dreb_pct': {
        'stat_category': 'basic',
        'display_name': 'DR%',
        'description': 'Defensive rebound percentage',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': 'd_rebound_pct_x1000 / 10',
            'team': 'd_rebound_pct_x1000 / 10',
        }
    },
    'cont_oreb_pct': {
        'stat_category': 'tracking',
        'display_name': 'COR%',
        'description': 'Contested offensive rebound % (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': '(cont_o_rebs / o_rebounds) * 100',
        },
    },
    'cont_dreb_pct': {
        'stat_category': 'tracking',
        'display_name': 'CDR%',
        'description': 'Contested defensive rebound % (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': '(cont_d_rebs / d_rebounds) * 100',
        },
    },
    'putbacks': {
        'stat_category': 'tracking',
        'display_name': 'PBS',
        'description': 'Putbacks per offensive rebound % (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rebounding',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'putbacks',
        },
    },
    'def_close_2fga': {
        'stat_category': 'tracking',
        'display_name': 'DC2A',
        'description': 'Defended close two-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'd_close_2fga',
        },
    },
    'points_per_def_close_2fga': {
        'stat_category': 'tracking',
        'display_name': 'PDC2',
        'description': 'Points allowed per defended close two',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': '2 * (d_close_2fgm / d_close_2fga)',
        },
    },
    'def_long_2fga': {
        'stat_category': 'tracking',
        'display_name': 'DL2A',
        'description': 'Defended long two-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'd_2fga - d_close_2fga',
        },
    },
    'points_per_def_long_2fga': {
        'stat_category': 'tracking',
        'display_name': 'PDL2',
        'description': 'Points allowed per defended long two',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': '2 * ((d_2fgm - d_close_2fgm) / (d_2fga - d_close_2fga))',
        },
    },
    'def_3fga': {
        'stat_category': 'tracking',
        'display_name': 'D3A',
        'description': 'Defended three-point attempts (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'd_3fga',
        },
    },
    'points_per_def_3fga': {
        'stat_category': 'tracking',
        'display_name': 'PD3',
        'description': 'Points allowed per defended three',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 2,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': '3 * (d_3fgm / d_3fga)',
        },
    },
    'real_def_pct': {
        'stat_category': 'tracking',
        'display_name': 'RD%',
        'description': 'Real defensive FG% (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'real_d_fg_pct_x1000 / 10',
        },
    },
    'real_def_close_2_pct': {
        'stat_category': 'tracking',
        'display_name': 'RDC2%',
        'description': 'Real defensive close two FG% +/- (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'real_d_close_2fg_pct_x1000 / 10',
        },
    },
    'real_def_2fg_pct': {
        'stat_category': 'tracking',
        'display_name': 'RD2%',
        'description': 'Real defensive 2pt FG% +/- (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'real_d_2fg_pct_x1000 / 10',
        },
    },
    'real_def_3fg_pct': {
        'stat_category': 'tracking',
        'display_name': 'RD3%',
        'description': 'Real defensive 3pt FG% +/- (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'real_d_3fg_pct_x1000 / 10',
        },
    },
    'blocks': {
        'stat_category': 'basic',
        'display_name': 'Blk',
        'description': 'Blocks',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': 'blocks',
            'team': 'blocks',
            'opponents': 'opp_blocks',
        }
    },
    'contests': {
        'stat_category': 'hustle',
        'display_name': 'Cont',
        'description': 'Shot contests (hustle)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'contests',
        },
    },
    'steals_plus_charges': {
        'stat_category': 'basic',
        'display_name': 'ST+C',
        'description': 'steals plus charges drawn',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'steals + charges_drawn',
        },
    },
    'deflections': {
        'stat_category': 'hustle',
        'display_name': 'DFLS',
        'description': 'Deflections (hustle)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'deflections',
        },
    },
    'fouls': {
        'stat_category': 'basic',
        'display_name': 'Fls',
        'description': 'Personal fouls',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': 'fouls',
            'team': 'fouls',
            'opponents': 'opp_fouls',
        }
    },
    'off_distance': {
        'stat_category': 'tracking',
        'display_name': 'ODST',
        'description': 'Offensive distance traveled in miles (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'movement',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'o_dist_x10 / 10',
        },
    },
    'def_distance': {
        'stat_category': 'tracking',
        'display_name': 'DDST',
        'description': 'Defensive distance traveled in miles (tracking)',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'movement',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'advanced',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'd_dist_x10 / 10',
        },
    },
    'o_rating': {
        'stat_category': 'basic',
        'display_name': 'ORT',
        'description': 'Offensive rating per 100 possessions',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': 'o_rating_x10 / 10',
            'team': 'o_rating_x10 / 10',
            'subsection': 'onoff',
        }
    },
    'd_rating': {
        'stat_category': 'basic',
        'display_name': 'DRT',
        'description': 'Defensive rating per 100 possessions',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba', 'ncaa'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
            'player': 'd_rating_x10 / 10',
            'team': 'd_rating_x10 / 10',
            'subsection': 'onoff',
        }
    },
    'net_off_o_rating': {
        'stat_category': 'basic',
        'display_name': 'NOOO',
        'description': 'Net Offensive on/off Team Rating',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'onoff',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': '(o_rating_x10 / 10) - (off_o_rating_x10 / 10)',
        },
    },
    'net_off_d_rating': {
        'stat_category': 'basic',
        'display_name': 'NDOO',
        'description': 'Net Defensive on/off Team Rating',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'onoff',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': '(d_rating_x10 / 10) - (off_d_rating_x10 / 10)',
        },
    },
    'nba_id': {
        'stat_category': 'none',
        'display_name': 'NBA ID',
        'description': 'NBA.com player/team ID',
        'section': ['identity'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'width_class': 'auto',
        'leagues': ['nba'],
        'team_row_calc': 'team_value',
        'nullable': False,
        'formulas': {
                'player': 'player_id',
        },
    },
    'conference': {
        'stat_category': 'none',
        'display_name': 'Conf',
        'description': 'conference',
        'section': ['player_info'],
        'subsection': None,
        'sheets': [],
        'stat_mode': 'both',
        'has_percentile': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'width_class': 'auto',
        'leagues': ['ncaa'],
        'nullable': False,
        'formulas': {
                'player': 'conference',
        },
    },
    'wins': {
        'stat_category': 'basic',
        'display_name': 'W',
        'description': 'Wins',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'sheets': ['all_teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'width_class': 'two_char',
        'leagues': ['ncaa'],
        'nullable': False,
        'formulas': {
                'team': 'wins',
        },
    },
    'losses': {
        'stat_category': 'basic',
        'display_name': 'L',
        'description': 'Losses',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'rates',
        'sheets': ['all_teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': True,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'width_class': 'two_char',
        'leagues': ['ncaa'],
        'nullable': False,
        'formulas': {
                'team': 'losses',
        },
    },
    'steals': {
        'stat_category': 'basic',
        'display_name': 'Stl',
        'description': 'Steals',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'defense',
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': True,
        'format': 'number',
        'decimal_places': 1,
        'width_class': 'three_char_dec',
        'leagues': ['ncaa'],
        'nullable': False,
        'formulas': {
                'player': 'steals',
        },
    },
    'win_pct': {
        'stat_category': 'basic',
        'display_name': 'W%',
        'description': 'Win percentage',
        'section': ['current_stats', 'historical_stats', 'postseason_stats'],
        'subsection': 'onoff',
        'sheets': ['all_teams', 'teams'],
        'stat_mode': 'both',
        'has_percentile': True,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'percentage',
        'decimal_places': 3,
        'width_class': 'three_char_dec',
        'leagues': ['ncaa'],
        'nullable': False,
        'formulas': {
                'team': 'wins / (wins + losses)',
        },
    },
    'ncaa_id': {
        'stat_category': 'none',
        'display_name': 'NCAA ID',
        'description': 'NCAA player/team ID',
        'section': ['identity'],
        'subsection': None,
        'sheets': ['all_teams', 'all_players', 'teams'],
        'stat_mode': 'both',
        'has_percentile': False,
        'editable': False,
        'reverse_percentile': False,
        'scale_with_mode': False,
        'format': 'number',
        'decimal_places': 0,
        'width_class': 'auto',
        'leagues': ['ncaa'],
        'nullable': False,
        'formulas': {
                'player': 'player_id',
        },
    },
}


def resolve_columns_for_league(league):
    """Resolve fully expanded SHEETS_COLUMNS into a league-specific flat dict."""
    from sheets.core.config import WIDTH_CLASSES
    resolved = {}

    for col_key, col_def in SHEETS_COLUMNS.items():
        leagues = col_def.get('leagues', ['nba', 'ncaa'])
        if league not in leagues:
            continue

        entry = {}
        _SKIP = {'leagues', 'formulas', 'width_class', 'width'}
        for k, v in col_def.items():
            if k not in _SKIP:
                entry[k] = v

        formulas = col_def.get('formulas', {})
        entry['player_formula'] = formulas.get('player')
        entry['team_formula'] = formulas.get('team')
        entry['opponents_formula'] = formulas.get('opponents')

        wc = col_def.get('width_class', 'auto')
        pw = WIDTH_CLASSES.get(wc)
        entry['minimum_width'] = pw if pw is not None else 'auto'

        resolved[col_key] = entry

    return resolved
